#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Boss_019

#include "Basic.hpp"

#include "MonsterAnimBP_Base_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Boss_019.ABP_Boss_019_C
// 0x0000 (0x62A0 - 0x62A0)
class UABP_Boss_019_C final : public UMonsterAnimBP_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Boss_019_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Boss_019_C")
	}
	static class UABP_Boss_019_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Boss_019_C>();
	}
};
DUMPER7_ASSERTS_UABP_Boss_019_C;

}

