#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FluxSolverRippleComponent

#include "Basic.hpp"

#include "BP_FluxSolverComponent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FluxSolverRippleComponent.BP_FluxSolverRippleComponent_C
// 0x0000 (0x0240 - 0x0240)
class UBP_FluxSolverRippleComponent_C final : public UBP_FluxSolverComponent_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FluxSolverRippleComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FluxSolverRippleComponent_C")
	}
	static class UBP_FluxSolverRippleComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FluxSolverRippleComponent_C>();
	}
};
DUMPER7_ASSERTS_UBP_FluxSolverRippleComponent_C;

}

