#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FluxNiagaraActor

#include "Basic.hpp"

#include "BP_FluxNiagaraActor_classes.hpp"
#include "BP_FluxNiagaraActor_parameters.hpp"


namespace SDK
{

// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_FluxNiagaraActor_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.StartReadback
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_FluxNiagaraActor_C::StartReadback()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "StartReadback");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.RestartNiagara
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_FluxNiagaraActor_C::RestartNiagara()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "RestartNiagara");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FluxNiagaraActor_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "ReceiveTick");

	Params::BP_FluxNiagaraActor_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.ReceiveParticleData
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FBasicParticleData>&Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UNiagaraSystem*                   NiagaraSystem_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   SimulationPositionOffset                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FluxNiagaraActor_C::ReceiveParticleData(const TArray<struct FBasicParticleData>& Data, class UNiagaraSystem* NiagaraSystem_0, const struct FVector& SimulationPositionOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "ReceiveParticleData");

	Params::BP_FluxNiagaraActor_C_ReceiveParticleData Parms{};

	Parms.Data = std::move(Data);
	Parms.NiagaraSystem_0 = NiagaraSystem_0;
	Parms.SimulationPositionOffset = std::move(SimulationPositionOffset);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_FluxNiagaraActor_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.OverlapingInteraction
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_FluxNiagaraActor_C::OverlapingInteraction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "OverlapingInteraction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.InitializeNiagara
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SurfaceAbstract                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_FluxNiagaraActor_C::InitializeNiagara(class AActor* SurfaceAbstract)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "InitializeNiagara");

	Params::BP_FluxNiagaraActor_C_InitializeNiagara Parms{};

	Parms.SurfaceAbstract = SurfaceAbstract;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.InitializeCollisions
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_FluxNiagaraActor_C::InitializeCollisions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "InitializeCollisions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.GetWorldSurface
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor**                          SurfaceAbstract                                        (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_FluxNiagaraActor_C::GetWorldSurface(class AActor** SurfaceAbstract)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "GetWorldSurface");

	Params::BP_FluxNiagaraActor_C_GetWorldSurface Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SurfaceAbstract != nullptr)
		*SurfaceAbstract = Parms.SurfaceAbstract;
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.ExecuteUbergraph_BP_FluxNiagaraActor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FluxNiagaraActor_C::ExecuteUbergraph_BP_FluxNiagaraActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "ExecuteUbergraph_BP_FluxNiagaraActor");

	Params::BP_FluxNiagaraActor_C_ExecuteUbergraph_BP_FluxNiagaraActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.BndEvt__BP_FluxNiagara_Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FluxNiagaraActor_C::BndEvt__BP_FluxNiagara_Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "BndEvt__BP_FluxNiagara_Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");

	Params::BP_FluxNiagaraActor_C_BndEvt__BP_FluxNiagara_Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.BndEvt__BP_FluxNiagara_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_FluxNiagaraActor_C::BndEvt__BP_FluxNiagara_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "BndEvt__BP_FluxNiagara_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_FluxNiagaraActor_C_BndEvt__BP_FluxNiagara_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.ApplyNiagaraData
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_FluxNiagaraActor_C::ApplyNiagaraData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "ApplyNiagaraData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FluxNiagaraActor.BP_FluxNiagaraActor_C.AdjustSize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_FluxNiagaraActor_C::AdjustSize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FluxNiagaraActor_C", "AdjustSize");

	UObject::ProcessEvent(Func, nullptr);
}

}

