#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FishWithSound

#include "Basic.hpp"

#include "BP_FishWithSound_classes.hpp"
#include "BP_FishWithSound_parameters.hpp"


namespace SDK
{

// Function BP_FishWithSound.BP_FishWithSound_C.ExecuteUbergraph_BP_FishWithSound
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FishWithSound_C::ExecuteUbergraph_BP_FishWithSound(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FishWithSound_C", "ExecuteUbergraph_BP_FishWithSound");

	Params::BP_FishWithSound_C_ExecuteUbergraph_BP_FishWithSound Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FishWithSound.BP_FishWithSound_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FishWithSound_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FishWithSound_C", "ReceiveTick");

	Params::BP_FishWithSound_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FishWithSound.BP_FishWithSound_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_FishWithSound_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FishWithSound_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

