#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TrafficMonsterMassSpawner

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TrafficMonsterMassSpawner.BP_TrafficMonsterMassSpawner_C
// 0x0000 (0x0568 - 0x0568)
class ABP_TrafficMonsterMassSpawner_C final : public AHTTrafficMonsterMassSpawner
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TrafficMonsterMassSpawner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TrafficMonsterMassSpawner_C")
	}
	static class ABP_TrafficMonsterMassSpawner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TrafficMonsterMassSpawner_C>();
	}
};
DUMPER7_ASSERTS_ABP_TrafficMonsterMassSpawner_C;

}

