#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TailDoor

#include "Basic.hpp"

#include "BP_TailDoor_classes.hpp"
#include "BP_TailDoor_parameters.hpp"


namespace SDK
{

// Function BP_TailDoor.BP_TailDoor_C.BndEvt__BP_TailDoor_Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TailDoor_C::BndEvt__BP_TailDoor_Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TailDoor_C", "BndEvt__BP_TailDoor_Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");

	Params::BP_TailDoor_C_BndEvt__BP_TailDoor_Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TailDoor.BP_TailDoor_C.BPGetInteractEntries
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTPlayerController*              ByPC                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<struct FInteractEntry>*          OutInteractEntries                                     (Parm, OutParm, ContainsInstancedReference)

void ABP_TailDoor_C::BPGetInteractEntries(class AHTPlayerController* ByPC, TArray<struct FInteractEntry>* OutInteractEntries)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TailDoor_C", "BPGetInteractEntries");

	Params::BP_TailDoor_C_BPGetInteractEntries Parms{};

	Parms.ByPC = ByPC;

	UObject::ProcessEvent(Func, &Parms);

	if (OutInteractEntries != nullptr)
		*OutInteractEntries = std::move(Parms.OutInteractEntries);
}


// Function BP_TailDoor.BP_TailDoor_C.BPInteractFinished
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AHTPlayerController*              ByPC                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   InteractIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TailDoor_C::BPInteractFinished(class AHTPlayerController* ByPC, int32 InteractIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TailDoor_C", "BPInteractFinished");

	Params::BP_TailDoor_C_BPInteractFinished Parms{};

	Parms.ByPC = ByPC;
	Parms.InteractIndex = InteractIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TailDoor.BP_TailDoor_C.ExecuteUbergraph_BP_TailDoor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TailDoor_C::ExecuteUbergraph_BP_TailDoor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TailDoor_C", "ExecuteUbergraph_BP_TailDoor");

	Params::BP_TailDoor_C_ExecuteUbergraph_BP_TailDoor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TailDoor.BP_TailDoor_C.OnLoaded_DEB16DFF4EA5590D893F5FB5631C24EA
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_TailDoor_C::OnLoaded_DEB16DFF4EA5590D893F5FB5631C24EA(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TailDoor_C", "OnLoaded_DEB16DFF4EA5590D893F5FB5631C24EA");

	Params::BP_TailDoor_C_OnLoaded_DEB16DFF4EA5590D893F5FB5631C24EA Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TailDoor.BP_TailDoor_C.OnLoaded_FE235D524F62A933473C6C95C2C02DB1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_TailDoor_C::OnLoaded_FE235D524F62A933473C6C95C2C02DB1(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TailDoor_C", "OnLoaded_FE235D524F62A933473C6C95C2C02DB1");

	Params::BP_TailDoor_C_OnLoaded_FE235D524F62A933473C6C95C2C02DB1 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TailDoor.BP_TailDoor_C.OnPlayDoorAnim
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bOpenDoor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TailDoor_C::OnPlayDoorAnim(bool bOpenDoor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TailDoor_C", "OnPlayDoorAnim");

	Params::BP_TailDoor_C_OnPlayDoorAnim Parms{};

	Parms.bOpenDoor = bOpenDoor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TailDoor.BP_TailDoor_C.PlayCloseSound
// (BlueprintCallable, BlueprintEvent)

void ABP_TailDoor_C::PlayCloseSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TailDoor_C", "PlayCloseSound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TailDoor.BP_TailDoor_C.PlayOpenSound
// (BlueprintCallable, BlueprintEvent)

void ABP_TailDoor_C::PlayOpenSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TailDoor_C", "PlayOpenSound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TailDoor.BP_TailDoor_C.Timeline__FinishedFunc
// (BlueprintEvent)

void ABP_TailDoor_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TailDoor_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TailDoor.BP_TailDoor_C.Timeline__UpdateFunc
// (BlueprintEvent)

void ABP_TailDoor_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TailDoor_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

