#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TrafficLightActor

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TrafficLightActor.BP_TrafficLightActor_C
// 0x0008 (0x02D0 - 0x02C8)
class ABP_TrafficLightActor_C final : public AActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TrafficLightActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TrafficLightActor_C")
	}
	static class ABP_TrafficLightActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TrafficLightActor_C>();
	}
};
DUMPER7_ASSERTS_ABP_TrafficLightActor_C;

}

