#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Vehicle_018_Module

#include "Basic.hpp"

#include "BP_Vehicle_018_Hight_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Vehicle_018_Module.BP_Vehicle_018_Module_C
// 0x0010 (0x1500 - 0x14F0)
class ABP_Vehicle_018_Module_C : public ABP_Vehicle_018_Hight_C
{
public:
	class UHTVehicleModificationComponent*        HTVehicleModification;                             // 0x14F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UHTVehicleForkEffectComponent*          HTVehicleForkEffect;                               // 0x14F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Vehicle_018_Module_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Vehicle_018_Module_C")
	}
	static class ABP_Vehicle_018_Module_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Vehicle_018_Module_C>();
	}
};
DUMPER7_ASSERTS_ABP_Vehicle_018_Module_C;

}

