#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ZeroGravityState

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ZeroGravityState.BP_ZeroGravityState_C
// 0x0000 (0x0118 - 0x0118)
class UBP_ZeroGravityState_C final : public UHTPlayerZeroGravityState
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ZeroGravityState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ZeroGravityState_C")
	}
	static class UBP_ZeroGravityState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ZeroGravityState_C>();
	}
};
DUMPER7_ASSERTS_UBP_ZeroGravityState_C;

}

