#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_VehicleNamePlate

#include "Basic.hpp"

#include "BPC_VehicleNamePlate_classes.hpp"
#include "BPC_VehicleNamePlate_parameters.hpp"


namespace SDK
{

// Function BPC_VehicleNamePlate.BPC_VehicleNamePlate_C.ExecuteUbergraph_BPC_VehicleNamePlate
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_VehicleNamePlate_C::ExecuteUbergraph_BPC_VehicleNamePlate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_VehicleNamePlate_C", "ExecuteUbergraph_BPC_VehicleNamePlate");

	Params::BPC_VehicleNamePlate_C_ExecuteUbergraph_BPC_VehicleNamePlate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_VehicleNamePlate.BPC_VehicleNamePlate_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBPC_VehicleNamePlate_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_VehicleNamePlate_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

