#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CallElevatorAI_SM_SLY

#include "Basic.hpp"


namespace SDK::Params
{

// Function CallElevatorAI_SM_SLY.CallElevatorAI_SM_SLY_C.BPOnMainRoleLoadFinished
// 0x0008 (0x0008 - 0x0000)
struct CallElevatorAI_SM_SLY_C_BPOnMainRoleLoadFinished final
{
public:
	class AHTPlayerState*                         PlayerState;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_CallElevatorAI_SM_SLY_C_BPOnMainRoleLoadFinished;

// Function CallElevatorAI_SM_SLY.CallElevatorAI_SM_SLY_C.ExecuteUbergraph_CallElevatorAI_SM_SLY
// 0x0020 (0x0020 - 0x0000)
struct CallElevatorAI_SM_SLY_C_ExecuteUbergraph_CallElevatorAI_SM_SLY final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0004(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AHTPlayerState*                         K2Node_Event_PlayerState;                          // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsQuestInProgress_ReturnValue;            // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_CallElevatorAI_SM_SLY_C_ExecuteUbergraph_CallElevatorAI_SM_SLY;

}

