#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Con_Boss01_IsNeedGuideForbiddenAtk

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Con_Boss01_IsNeedGuideForbiddenAtk.Con_Boss01_IsNeedGuideForbiddenAtk_C
// 0x0010 (0x0040 - 0x0030)
class UCon_Boss01_IsNeedGuideForbiddenAtk_C final : public UHTGameplayEffectCustomApplicationRequirement
{
public:
	class FName                                   Guide_ID;                                          // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Guide_ID_0;                                        // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool CanApplyGameplayEffectContent(class AActor* SourceActor, class AActor* TargetActor, class AActor* InstigatorActor, const class UGameplayEffect* GameplayEffect) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Con_Boss01_IsNeedGuideForbiddenAtk_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Con_Boss01_IsNeedGuideForbiddenAtk_C")
	}
	static class UCon_Boss01_IsNeedGuideForbiddenAtk_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCon_Boss01_IsNeedGuideForbiddenAtk_C>();
	}
};
DUMPER7_ASSERTS_UCon_Boss01_IsNeedGuideForbiddenAtk_C;

}

