#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CriWareMana

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CriWareMana_structs.hpp"
#include "DeveloperSettings_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "CriWareCore_classes.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// Class CriWareMana.CriWareManaSettings
// 0x0018 (0x0050 - 0x0038)
class UCriWareManaSettings final : public UDeveloperSettings
{
public:
	bool                                          bEnableLoggingMana;                                // 0x0038(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCriWareManaMovieSettings              ManaMovieSettings;                                 // 0x003C(0x0010)(Edit, Config, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CriWareManaSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CriWareManaSettings")
	}
	static class UCriWareManaSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCriWareManaSettings>();
	}
};
DUMPER7_ASSERTS_UCriWareManaSettings;

// Class CriWareMana.ManaComponentTexture
// 0x0058 (0x01B0 - 0x0158)
class UManaComponentTexture final : public UTexture
{
public:
	int32                                         SizeX;                                             // 0x0158(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SizeY;                                             // 0x015C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPixelFormat                                  Format;                                            // 0x0160(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EManaComponentTextureType                     ComponentType;                                     // 0x0161(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ETextureAddress                               AddressX;                                          // 0x0162(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, AssetRegistrySearchable, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ETextureAddress                               AddressY;                                          // 0x0163(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, AssetRegistrySearchable, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_164[0x4C];                                     // 0x0164(0x004C)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaComponentTexture")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaComponentTexture")
	}
	static class UManaComponentTexture* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaComponentTexture>();
	}
};
DUMPER7_ASSERTS_UManaComponentTexture;

// Class CriWareMana.ManaEventPointComponent
// 0x0078 (0x0138 - 0x00C0)
class UManaEventPointComponent final : public UActorComponent
{
public:
	uint8                                         bAutoDestroy : 1;                                  // 0x00C0(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const struct FManaEventPointInfo& EventPointInfo)> OnEventPointReceived; // 0x00C8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	class UManaPlayer*                            ManaPlayer;                                        // 0x00D8(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_E0[0x58];                                      // 0x00E0(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetManaPlayer(class UManaPlayer* NewManaPlayer);

	class UManaPlayer* GetManaPlayer() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaEventPointComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaEventPointComponent")
	}
	static class UManaEventPointComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaEventPointComponent>();
	}
};
DUMPER7_ASSERTS_UManaEventPointComponent;

// Class CriWareMana.ManaPlayerProxyInterface
// 0x0000 (0x0000 - 0x0000)
class IManaPlayerProxyInterface final
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaPlayerProxyInterface")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaPlayerProxyInterface")
	}
	static class IManaPlayerProxyInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<IManaPlayerProxyInterface>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IManaPlayerProxyInterface;

// Class CriWareMana.ManaSource
// 0x0000 (0x0028 - 0x0028)
class UManaSource : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaSource")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaSource")
	}
	static class UManaSource* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaSource>();
	}
};
DUMPER7_ASSERTS_UManaSource;

// Class CriWareMana.ManaPlaylist
// 0x0018 (0x0040 - 0x0028)
class UManaPlaylist final : public UManaSource
{
public:
	TArray<class UManaMovie*>                     Movies;                                            // 0x0028(0x0010)(Edit, ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	bool                                          bIsAlpha;                                          // 0x0038(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsMixedTypes;                                     // 0x0039(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsSeamless;                                       // 0x003A(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_3B[0x5];                                       // 0x003B(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool Add(class UManaMovie* ManaMovie);
	bool AddFile(const class FString& FilePath);
	bool AddUrl(const class FString& URL);
	class UManaMovie* Get(int32 Index_0);
	class UManaMovie* GetNext(int32* InOutIndex);
	class UManaMovie* GetPrevious(int32* InOutIndex);
	class UManaMovie* GetRandom(int32* InOutIndex);
	void Insert(class UManaMovie* ManaMovie, int32 Index_0);
	bool IsAlpha();
	bool IsMixedTypes();
	bool IsSeamless();
	int32 Num();
	bool Remove(class UManaMovie* ManaMovie);
	bool RemoveAt(int32 Index_0);
	bool Replace(int32 Index_0, class UManaMovie* Replacement);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaPlaylist")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaPlaylist")
	}
	static class UManaPlaylist* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaPlaylist>();
	}
};
DUMPER7_ASSERTS_UManaPlaylist;

// Class CriWareMana.ManaSoundComponent
// 0x0090 (0x07E0 - 0x0750)
class UManaSoundComponent final : public UAtomExternalComponent
{
public:
	EManaSoundTracks                              SoundTrack;                                        // 0x0748(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_74C[0x4];                                      // 0x074C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UManaPlayer*                            ManaPlayer;                                        // 0x0750(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_758[0x88];                                     // 0x0758(0x0088)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool BP_GetAttenuationSettingsToApply(struct FAtomAttenuationSettings* OutAttenuationSettings);
	void SetManaPlayer(class UManaPlayer* NewManaPlayer);

	class UManaPlayer* GetManaPlayer() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaSoundComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaSoundComponent")
	}
	static class UManaSoundComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaSoundComponent>();
	}
};
DUMPER7_ASSERTS_UManaSoundComponent;

// Class CriWareMana.ManaSourceRendererInterface
// 0x0000 (0x0000 - 0x0000)
class IManaSourceRendererInterface final
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaSourceRendererInterface")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaSourceRendererInterface")
	}
	static class IManaSourceRendererInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<IManaSourceRendererInterface>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IManaSourceRendererInterface;

// Class CriWareMana.ManaSubtitleComponent
// 0x0088 (0x0148 - 0x00C0)
class UManaSubtitleComponent final : public UActorComponent
{
public:
	uint8                                         bAutoDestroy : 1;                                  // 0x00C0(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class FText Subtitle)> OnSubtitleChanged;                          // 0x00C8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	class UManaPlayer*                            ManaPlayer;                                        // 0x00D8(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_E0[0x68];                                      // 0x00E0(0x0068)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetManaPlayer(class UManaPlayer* NewManaPlayer);

	class FText GetCurrentSubtitle() const;
	class UManaPlayer* GetManaPlayer() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaSubtitleComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaSubtitleComponent")
	}
	static class UManaSubtitleComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaSubtitleComponent>();
	}
};
DUMPER7_ASSERTS_UManaSubtitleComponent;

// Class CriWareMana.ManaSubtitleTextBlock
// 0x0608 (0x0790 - 0x0188)
class UManaSubtitleTextBlock final : public UTextLayoutWidget
{
public:
	class UManaPlayer*                            ManaPlayer;                                        // 0x0188(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bOverrideDefaultStyle;                             // 0x0190(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_191[0xF];                                      // 0x0191(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTextBlockStyle                        DefaultTextStyleOverride;                          // 0x01A0(0x02E0)(Edit, Protected, NativeAccessSpecifierProtected)
	float                                         MinDesiredWidth;                                   // 0x0480(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	ETextTransformPolicy                          TextTransformPolicy;                               // 0x0484(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	ETextOverflowPolicy                           TextOverflowPolicy;                                // 0x0485(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_486[0xA];                                      // 0x0486(0x000A)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTextBlockStyle                        DefaultTextStyle;                                  // 0x0490(0x02E0)(Transient, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_770[0x20];                                     // 0x0770(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	class FText GetText() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaSubtitleTextBlock")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaSubtitleTextBlock")
	}
	static class UManaSubtitleTextBlock* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaSubtitleTextBlock>();
	}
};
DUMPER7_ASSERTS_UManaSubtitleTextBlock;

// Class CriWareMana.ManaTexture
// 0x0160 (0x02B8 - 0x0158)
class UManaTexture final : public UTexture
{
public:
	ETextureAddress                               AddressX;                                          // 0x0158(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AssetRegistrySearchable, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ETextureAddress                               AddressY;                                          // 0x0159(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AssetRegistrySearchable, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          AutoClear;                                         // 0x015A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15B[0x1];                                      // 0x015B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           ClearColor;                                        // 0x015C(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AssetRegistrySearchable, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          EnableGenMips;                                     // 0x016C(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         NumMips;                                           // 0x016D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16E[0x2];                                      // 0x016E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	uint8                                         bRenderToTexture : 1;                              // 0x0170(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_171[0x3];                                      // 0x0171(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TargetGamma;                                       // 0x0174(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         bHDR : 1;                                          // 0x0178(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, AssetRegistrySearchable, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bOverrideDimensions : 1;                           // 0x0178(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, BlueprintVisible, NoDestructor, AssetRegistrySearchable, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_179[0x3];                                      // 0x0179(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FIntPoint                              TargetDimensions;                                  // 0x017C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AssetRegistrySearchable, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CurrentAspectRatio;                                // 0x0184(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, TextExportTransient, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EManaTextureOrientation                       CurrentOrientation;                                // 0x0188(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, TextExportTransient, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPixelFormat                                  OverrideFormat;                                    // 0x018C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_18D[0x3];                                      // 0x018D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class UManaTexture* ManaTexture)> OnTextureUpdated;                // 0x0190(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A0[0x28];                                     // 0x01A0(0x0028)(Fixing Size After Last Property [ Dumper-7 ])
	class UManaPlayer*                            ManaPlayer;                                        // 0x01C8(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class FString                                 MovieFilePath;                                     // 0x01D0(0x0010)(ZeroConstructor, Deprecated, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UManaComponentTexture*                  ComponentTextures[0x3];                            // 0x01E0(0x0008)(Edit, ZeroConstructor, EditConst, NoDestructor, AdvancedDisplay, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UManaComponentTexture*                  AlphaComponentTextures[0x3];                       // 0x01F8(0x0008)(Edit, ZeroConstructor, EditConst, NoDestructor, AdvancedDisplay, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_210[0xA8];                                     // 0x0210(0x00A8)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetManaPlayer(class UManaPlayer* NewManaPlayer);
	void UpdateResource();

	float GetAspectRatio() const;
	int32 GetHeight() const;
	class UManaPlayer* GetManaPlayer() const;
	int32 GetTextureNumMips() const;
	int32 GetWidth() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaTexture")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaTexture")
	}
	static class UManaTexture* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaTexture>();
	}
};
DUMPER7_ASSERTS_UManaTexture;

// Class CriWareMana.MaterialExpressionManaColorSpaceConverter
// 0x00D0 (0x0180 - 0x00B0)
class UMaterialExpressionManaColorSpaceConverter final : public UMaterialExpression
{
public:
	struct FExpressionInput                       Luma;                                              // 0x00B0(0x0028)(NoDestructor, NativeAccessSpecifierPublic)
	struct FExpressionInput                       ChromaB;                                           // 0x00D8(0x0028)(NoDestructor, NativeAccessSpecifierPublic)
	struct FExpressionInput                       ChromaR;                                           // 0x0100(0x0028)(NoDestructor, NativeAccessSpecifierPublic)
	struct FExpressionInput                       Alpha;                                             // 0x0128(0x0028)(NoDestructor, NativeAccessSpecifierPublic)
	struct FExpressionInput                       Gamma;                                             // 0x0150(0x0028)(NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bH264;                                             // 0x0178(0x0001)(ZeroConstructor, Deprecated, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EManaMovieType                                MovieType;                                         // 0x0179(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EManaColorSpace                               ColorSpace;                                        // 0x017A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseGammaExponent;                                 // 0x017B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ConstGamma;                                        // 0x017C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MaterialExpressionManaColorSpaceConverter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MaterialExpressionManaColorSpaceConverter")
	}
	static class UMaterialExpressionManaColorSpaceConverter* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMaterialExpressionManaColorSpaceConverter>();
	}
};
DUMPER7_ASSERTS_UMaterialExpressionManaColorSpaceConverter;

// Class CriWareMana.ManaMovie
// 0x00C0 (0x00E8 - 0x0028)
class UManaMovie : public UManaSource
{
public:
	uint8                                         Pad_28[0x8];                                       // 0x0028(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FManaVideoTrackInfo>            VideoTracks;                                       // 0x0030(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, Protected, NativeAccessSpecifierProtected)
	TArray<struct FManaVideoTrackInfo>            AlphaTracks;                                       // 0x0040(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, Protected, NativeAccessSpecifierProtected)
	TArray<struct FManaAudioTrackInfo>            AudioTracks;                                       // 0x0050(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, EditFixedSize, ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	TArray<struct FManaEventPointInfo>            EventPoints;                                       // 0x0060(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, EditFixedSize, ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	TArray<struct FManaSubtitleTrackInfo>         SubtitleTracks;                                    // 0x0070(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, EditFixedSize, ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	int32                                         NumSubtitleChannels;                               // 0x0080(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         MaxSubtitleSize;                                   // 0x0084(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         MinBufferSize;                                     // 0x0088(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, AdvancedDisplay, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         MaxChunkSize;                                      // 0x008C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, AdvancedDisplay, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         bIsAlpha : 1;                                      // 0x0090(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, BlueprintReadOnly, EditConst, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected))
	uint8                                         Pad_91[0x57];                                      // 0x0091(0x0057)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetManaOptionBool(const class FName& Key, bool Value);
	void SetManaOptionFloat(const class FName& Key, float Value);
	void SetManaOptionInt64(const class FName& Key, int64 Value);
	void SetManaOptionString(const class FName& Key, const class FString& Value);

	class FString GetUrl() const;
	bool Validate() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaMovie")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaMovie")
	}
	static class UManaMovie* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaMovie>();
	}
};
DUMPER7_ASSERTS_UManaMovie;

// Class CriWareMana.PlatformManaMovie
// 0x0008 (0x00F0 - 0x00E8)
class UPlatformManaMovie final : public UManaMovie
{
public:
	class UManaMovie*                             ManaMovie;                                         // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PlatformManaMovie")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PlatformManaMovie")
	}
	static class UPlatformManaMovie* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlatformManaMovie>();
	}
};
DUMPER7_ASSERTS_UPlatformManaMovie;

// Class CriWareMana.ManaComponent
// 0x0010 (0x00D0 - 0x00C0)
class UManaComponent final : public UActorComponent
{
public:
	class UManaTexture*                           ManaTexture;                                       // 0x00C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, Transient, InstancedReference, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UManaPlayer*                            ManaPlayer;                                        // 0x00C8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, Transient, InstancedReference, Interp, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	class UManaPlayer* GetManaPlayer() const;
	class UManaTexture* GetManaTexture() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaComponent")
	}
	static class UManaComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaComponent>();
	}
};
DUMPER7_ASSERTS_UManaComponent;

// Class CriWareMana.FileManaMovie
// 0x0028 (0x0110 - 0x00E8)
class UFileManaMovie final : public UManaMovie
{
public:
	bool                                          bPrecacheFile;                                     // 0x00E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 FilePath;                                          // 0x00F0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, AssetRegistrySearchable, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_100[0x10];                                     // 0x0100(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetFilePath(const class FString& Path);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FileManaMovie")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FileManaMovie")
	}
	static class UFileManaMovie* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFileManaMovie>();
	}
};
DUMPER7_ASSERTS_UFileManaMovie;

// Class CriWareMana.DataManaMovie
// 0x0008 (0x00F0 - 0x00E8)
class UDataManaMovie final : public UManaMovie
{
public:
	uint8                                         Pad_E8[0x8];                                       // 0x00E8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetDataArray(TArray<uint8>& InDataArray);

	TArray<uint8> GetDataArray() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("DataManaMovie")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DataManaMovie")
	}
	static class UDataManaMovie* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDataManaMovie>();
	}
};
DUMPER7_ASSERTS_UDataManaMovie;

// Class CriWareMana.StreamManaMovie
// 0x0010 (0x00F8 - 0x00E8)
class UStreamManaMovie final : public UManaMovie
{
public:
	class FString                                 StreamUrl;                                         // 0x00E8(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, AssetRegistrySearchable, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("StreamManaMovie")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StreamManaMovie")
	}
	static class UStreamManaMovie* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStreamManaMovie>();
	}
};
DUMPER7_ASSERTS_UStreamManaMovie;

// Class CriWareMana.ManaTimeStampInfo
// 0x0010 (0x0038 - 0x0028)
class UManaTimeStampInfo final : public UObject
{
public:
	struct FTimespan                              Time;                                              // 0x0028(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         SequenceIndex;                                     // 0x0030(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaTimeStampInfo")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaTimeStampInfo")
	}
	static class UManaTimeStampInfo* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaTimeStampInfo>();
	}
};
DUMPER7_ASSERTS_UManaTimeStampInfo;

// Class CriWareMana.ManaPlayer
// 0x0130 (0x0158 - 0x0028)
class UManaPlayer final : public UObject
{
public:
	TMulticastInlineDelegate<void()>              OnEndReached;                                      // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnMovieClosed;                                     // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& OpenedUrl)> OnMovieOpened;                    // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& FailedUrl)> OnMovieOpenFailed;                // 0x0058(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnPlaybackResumed;                                 // 0x0068(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnPlaybackSuspended;                               // 0x0078(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnSeekCompleted;                                   // 0x0088(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnTracksChanged;                                   // 0x0098(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnMetadataChanged;                                 // 0x00A8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnBufferingStart;                                  // 0x00B8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnBufferingCompleted;                              // 0x00C8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	bool                                          PlayOnOpen;                                        // 0x00D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D9[0x3];                                       // 0x00D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	uint8                                         Shuffle : 1;                                       // 0x00DC(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Loop : 1;                                          // 0x00DC(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected))
	uint8                                         Pad_DD[0x3];                                       // 0x00DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UManaPlaylist*                          Playlist;                                          // 0x00E0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         PlaylistIndex;                                     // 0x00E8(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_EC[0x4];                                       // 0x00EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimespan                              TimeDelay;                                         // 0x00F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         HorizontalFieldOfView;                             // 0x00F8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         VerticalFieldOfView;                               // 0x00FC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FRotator                               ViewRotation;                                      // 0x0100(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_118[0x28];                                     // 0x0118(0x0028)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGuid                                  PlayerGuid;                                        // 0x0140(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_150[0x8];                                      // 0x0150(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool CanPlaySource(class UManaMovie* MediaSource);
	bool CanPlayUrl(const class FString& URL);
	void Close();
	struct FFloatInterval GetPlaybackTimeRange(EManaTimeRangeBPType InRangeToGet);
	bool Next();
	bool OpenFile(const class FString& FilePath);
	bool OpenPlaylist(class UManaPlaylist* InPlaylist);
	bool OpenPlaylistIndex(class UManaPlaylist* InPlaylist, int32 Index_0);
	bool OpenSource(class UManaMovie* MediaSource);
	void OpenSourceLatent(const class UObject* WorldContextObject, const struct FLatentActionInfo& LatentInfo, class UManaMovie* MediaSource, const struct FManaPlayerOptions& Options, bool* bSuccess);
	bool OpenSourceWithOptions(class UManaMovie* MediaSource, const struct FManaPlayerOptions& Options);
	bool OpenUrl(const class FString& URL);
	bool Pause();
	bool Play();
	void PlayAndSeek();
	bool Previous();
	bool Reopen();
	bool Rewind();
	bool Scrub(const struct FTimespan& Time);
	bool Seek(const struct FTimespan& Time);
	bool SelectTrack(EManaPlayerTrack TrackType, int32 TrackIndex);
	void SetBlockOnTime(const struct FTimespan& Time);
	bool SetLooping(bool Looping);
	void SetManaOptions(const class UManaMovie* Options);
	bool SetNativeVolume(float Volume);
	bool SetPlaybackTimeRange(const struct FFloatInterval& InTimeRange);
	bool SetRate(float Rate);
	void SetTimeDelay(const struct FTimespan& TimeDelay_0);
	bool SetTrackFormat(EManaPlayerTrack TrackType, int32 TrackIndex, int32 FormatIndex);
	bool SetVideoTrackFrameRate(int32 TrackIndex, int32 FormatIndex, float FrameRate);
	bool SetViewField(float Horizontal, float Vertical, bool Absolute);
	bool SetViewRotation(const struct FRotator& Rotation, bool Absolute);

	bool CanPause() const;
	int32 GetAudioTrackChannels(int32 TrackIndex, int32 FormatIndex) const;
	int32 GetAudioTrackSampleRate(int32 TrackIndex, int32 FormatIndex) const;
	class FString GetAudioTrackType(int32 TrackIndex, int32 FormatIndex) const;
	struct FTimespan GetDisplayTime() const;
	class UManaTimeStampInfo* GetDisplayTimeStamp() const;
	struct FTimespan GetDuration() const;
	float GetHorizontalFieldOfView() const;
	TMap<class FString, struct FManaMetadataItemsBPT> GetManaMetadataItems() const;
	class FText GetManaSourceName() const;
	int32 GetNumTrackFormats(EManaPlayerTrack TrackType, int32 TrackIndex) const;
	int32 GetNumTracks(EManaPlayerTrack TrackType) const;
	class FName GetPlayerName() const;
	class UManaPlaylist* GetPlaylist() const;
	int32 GetPlaylistIndex() const;
	float GetRate() const;
	int32 GetSelectedTrack(EManaPlayerTrack TrackType) const;
	void GetSupportedRates(TArray<struct FFloatRange>* OutRates, bool Unthinned) const;
	struct FTimespan GetTime() const;
	struct FTimespan GetTimeDelay() const;
	class UManaTimeStampInfo* GetTimeStamp() const;
	class FText GetTrackDisplayName(EManaPlayerTrack TrackType, int32 TrackIndex) const;
	int32 GetTrackFormat(EManaPlayerTrack TrackType, int32 TrackIndex) const;
	class FString GetTrackLanguage(EManaPlayerTrack TrackType, int32 TrackIndex) const;
	class FString GetUrl() const;
	float GetVerticalFieldOfView() const;
	float GetVideoTrackAspectRatio(int32 TrackIndex, int32 FormatIndex) const;
	struct FIntPoint GetVideoTrackDimensions(int32 TrackIndex, int32 FormatIndex) const;
	float GetVideoTrackFrameRate(int32 TrackIndex, int32 FormatIndex) const;
	struct FFloatRange GetVideoTrackFrameRates(int32 TrackIndex, int32 FormatIndex) const;
	class FString GetVideoTrackType(int32 TrackIndex, int32 FormatIndex) const;
	struct FRotator GetViewRotation() const;
	bool HasError() const;
	bool IsBuffering() const;
	bool IsClosed() const;
	bool IsConnecting() const;
	bool IsLooping() const;
	bool IsPaused() const;
	bool IsPlaying() const;
	bool IsPreparing() const;
	bool IsReady() const;
	bool SupportsPlaybackTimeRange() const;
	bool SupportsRate(float Rate, bool Unthinned) const;
	bool SupportsScrubbing() const;
	bool SupportsSeeking() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ManaPlayer")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ManaPlayer")
	}
	static class UManaPlayer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UManaPlayer>();
	}
};
DUMPER7_ASSERTS_UManaPlayer;

}

