#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_AnalyticFogShape

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_AnalyticFogShape.E_AnalyticFogShape
// NumValues: 0x0010
enum class E_AnalyticFogShape : uint8
{
	NewEnumerator10                          = 0,
	NewEnumerator1                           = 1,
	NewEnumerator5                           = 2,
	NewEnumerator11                          = 3,
	NewEnumerator14                          = 4,
	NewEnumerator15                          = 5,
	NewEnumerator16                          = 6,
	NewEnumerator17                          = 7,
	NewEnumerator18                          = 8,
	NewEnumerator19                          = 9,
	NewEnumerator20                          = 10,
	NewEnumerator21                          = 11,
	NewEnumerator22                          = 12,
	NewEnumerator23                          = 13,
	NewEnumerator24                          = 14,
	E_MAX                                    = 15,
};

}

