#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_MontageBase

#include "Basic.hpp"

#include "GA_MontageBase_classes.hpp"
#include "GA_MontageBase_parameters.hpp"


namespace SDK
{

// Function GA_MontageBase.GA_MontageBase_C.TriggerJumpSectionImpl
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             JumpSectionName                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_MontageBase_C::TriggerJumpSectionImpl(class FName JumpSectionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "TriggerJumpSectionImpl");

	Params::GA_MontageBase_C_TriggerJumpSectionImpl Parms{};

	Parms.JumpSectionName = JumpSectionName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_MontageBase.GA_MontageBase_C.OnTriggerNextSection_A46B470745030951E66252ABC1169A79
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NextSectionName                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_MontageBase_C::OnTriggerNextSection_A46B470745030951E66252ABC1169A79(class FName NextSectionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "OnTriggerNextSection_A46B470745030951E66252ABC1169A79");

	Params::GA_MontageBase_C_OnTriggerNextSection_A46B470745030951E66252ABC1169A79 Parms{};

	Parms.NextSectionName = NextSectionName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_MontageBase.GA_MontageBase_C.OnReleaseFire_F412C28D45D0207108BE7F8920600ACE
// (BlueprintCallable, BlueprintEvent)

void UGA_MontageBase_C::OnReleaseFire_F412C28D45D0207108BE7F8920600ACE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "OnReleaseFire_F412C28D45D0207108BE7F8920600ACE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_MontageBase.GA_MontageBase_C.OnRelease_09EC101B4BF38E1DD11EF9AD3FC2BBA1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   TimeHeld                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bAuto                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_MontageBase_C::OnRelease_09EC101B4BF38E1DD11EF9AD3FC2BBA1(float TimeHeld, bool bAuto)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "OnRelease_09EC101B4BF38E1DD11EF9AD3FC2BBA1");

	Params::GA_MontageBase_C_OnRelease_09EC101B4BF38E1DD11EF9AD3FC2BBA1 Parms{};

	Parms.TimeHeld = TimeHeld;
	Parms.bAuto = bAuto;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_MontageBase.GA_MontageBase_C.OnReceiveEvent
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              ContainerTag                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayEventData&        EventData                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_MontageBase_C::OnReceiveEvent(const struct FGameplayTag& ContainerTag, const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "OnReceiveEvent");

	Params::GA_MontageBase_C_OnReceiveEvent Parms{};

	Parms.ContainerTag = std::move(ContainerTag);
	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_MontageBase.GA_MontageBase_C.OnInterrupted_F7C45E2243E75F2961A2289F04DE722F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              EventTag                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayEventData&        EventData                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_MontageBase_C::OnInterrupted_F7C45E2243E75F2961A2289F04DE722F(const struct FGameplayTag& EventTag, const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "OnInterrupted_F7C45E2243E75F2961A2289F04DE722F");

	Params::GA_MontageBase_C_OnInterrupted_F7C45E2243E75F2961A2289F04DE722F Parms{};

	Parms.EventTag = std::move(EventTag);
	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_MontageBase.GA_MontageBase_C.OnEnterAiming_F412C28D45D0207108BE7F8920600ACE
// (BlueprintCallable, BlueprintEvent)

void UGA_MontageBase_C::OnEnterAiming_F412C28D45D0207108BE7F8920600ACE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "OnEnterAiming_F412C28D45D0207108BE7F8920600ACE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_MontageBase.GA_MontageBase_C.OnCompleted_F7C45E2243E75F2961A2289F04DE722F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              EventTag                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayEventData&        EventData                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_MontageBase_C::OnCompleted_F7C45E2243E75F2961A2289F04DE722F(const struct FGameplayTag& EventTag, const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "OnCompleted_F7C45E2243E75F2961A2289F04DE722F");

	Params::GA_MontageBase_C_OnCompleted_F7C45E2243E75F2961A2289F04DE722F Parms{};

	Parms.EventTag = std::move(EventTag);
	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_MontageBase.GA_MontageBase_C.OnCancelled_F7C45E2243E75F2961A2289F04DE722F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              EventTag                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayEventData&        EventData                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_MontageBase_C::OnCancelled_F7C45E2243E75F2961A2289F04DE722F(const struct FGameplayTag& EventTag, const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "OnCancelled_F7C45E2243E75F2961A2289F04DE722F");

	Params::GA_MontageBase_C_OnCancelled_F7C45E2243E75F2961A2289F04DE722F Parms{};

	Parms.EventTag = std::move(EventTag);
	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_MontageBase.GA_MontageBase_C.OnBlendOut_F7C45E2243E75F2961A2289F04DE722F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              EventTag                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayEventData&        EventData                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_MontageBase_C::OnBlendOut_F7C45E2243E75F2961A2289F04DE722F(const struct FGameplayTag& EventTag, const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "OnBlendOut_F7C45E2243E75F2961A2289F04DE722F");

	Params::GA_MontageBase_C_OnBlendOut_F7C45E2243E75F2961A2289F04DE722F Parms{};

	Parms.EventTag = std::move(EventTag);
	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_MontageBase.GA_MontageBase_C.K2_TriggerJumpSection
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             JumpSectionName                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_MontageBase_C::K2_TriggerJumpSection(class FName JumpSectionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "K2_TriggerJumpSection");

	Params::GA_MontageBase_C_K2_TriggerJumpSection Parms{};

	Parms.JumpSectionName = JumpSectionName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_MontageBase.GA_MontageBase_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_MontageBase_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_MontageBase.GA_MontageBase_C.IsOwnerAiming
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   IsAiming                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_MontageBase_C::IsOwnerAiming(bool* IsAiming)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "IsOwnerAiming");

	Params::GA_MontageBase_C_IsOwnerAiming Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsAiming != nullptr)
		*IsAiming = Parms.IsAiming;
}


// Function GA_MontageBase.GA_MontageBase_C.ExecuteUbergraph_GA_MontageBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_MontageBase_C::ExecuteUbergraph_GA_MontageBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "ExecuteUbergraph_GA_MontageBase");

	Params::GA_MontageBase_C_ExecuteUbergraph_GA_MontageBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_MontageBase.GA_MontageBase_C.EventReceived_F7C45E2243E75F2961A2289F04DE722F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              EventTag                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayEventData&        EventData                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_MontageBase_C::EventReceived_F7C45E2243E75F2961A2289F04DE722F(const struct FGameplayTag& EventTag, const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "EventReceived_F7C45E2243E75F2961A2289F04DE722F");

	Params::GA_MontageBase_C_EventReceived_F7C45E2243E75F2961A2289F04DE722F Parms{};

	Parms.EventTag = std::move(EventTag);
	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_MontageBase.GA_MontageBase_C.CanExec
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   can                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_MontageBase_C::CanExec(bool* can)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_MontageBase_C", "CanExec");

	Params::GA_MontageBase_C_CanExec Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (can != nullptr)
		*can = Parms.can;
}

}

