#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HathorMelee4_2HitDown

#include "Basic.hpp"

#include "SkillEffect_HitDown_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HathorMelee4_2HitDown.HathorMelee4_2HitDown_C
// 0x0000 (0x0230 - 0x0230)
class UHathorMelee4_2HitDown_C final : public USkillEffect_HitDown_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HathorMelee4_2HitDown_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HathorMelee4_2HitDown_C")
	}
	static class UHathorMelee4_2HitDown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHathorMelee4_2HitDown_C>();
	}
};
DUMPER7_ASSERTS_UHathorMelee4_2HitDown_C;

}

