#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HTCameraSettingModifier_ParryAttack_Boss_019

#include "Basic.hpp"

#include "HTCameraSettingModifier_ParryAttack_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HTCameraSettingModifier_ParryAttack_Boss_019.HTCameraSettingModifier_ParryAttack_Boss_019_C
// 0x0000 (0x0AB8 - 0x0AB8)
class UHTCameraSettingModifier_ParryAttack_Boss_019_C final : public UHTCameraSettingModifier_ParryAttack_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HTCameraSettingModifier_ParryAttack_Boss_019_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HTCameraSettingModifier_ParryAttack_Boss_019_C")
	}
	static class UHTCameraSettingModifier_ParryAttack_Boss_019_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHTCameraSettingModifier_ParryAttack_Boss_019_C>();
	}
};
DUMPER7_ASSERTS_UHTCameraSettingModifier_ParryAttack_Boss_019_C;

}

