#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HTFishAnimLayer__051_male_BP

#include "Basic.hpp"

#include "BP_HTFishAnimLayer_structs.hpp"


namespace SDK
{

// ScriptStruct HTFishAnimLayer__051_male_BP.HTFishAnimLayer__051_male_BP_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0BB8 - 0x0BB8)
struct HTFishAnimLayer__051_male_BP::FAnimBlueprintGeneratedConstantData final : public BP_HTFishAnimLayer::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_HTFishAnimLayer__051_male_BP__FAnimBlueprintGeneratedConstantData;

}

