#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HTSwim_AnimLayer_051_female_BP

#include "Basic.hpp"

#include "HTSwimAnimLayerBase_structs.hpp"


namespace SDK
{

// ScriptStruct HTSwim_AnimLayer_051_female_BP.HTSwim_AnimLayer_051_female_BP_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x06B0 - 0x06B0)
struct HTSwim_AnimLayer_051_female_BP::FAnimBlueprintGeneratedConstantData final : public HTSwimAnimLayerBase::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_HTSwim_AnimLayer_051_female_BP__FAnimBlueprintGeneratedConstantData;

}

