#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_002_AnimBP

#include "Basic.hpp"

#include "NPCAnimBP_Base_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass NPC_002_AnimBP.NPC_002_AnimBP_C
// 0x0010 (0x4340 - 0x4330)
class UNPC_002_AnimBP_C final : public UNPCAnimBP_Base_C
{
public:
	class FName                                   Fts_GroundMaterial_Switch;                         // 0x4330(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void GetMaterial();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NPC_002_AnimBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NPC_002_AnimBP_C")
	}
	static class UNPC_002_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNPC_002_AnimBP_C>();
	}
};
DUMPER7_ASSERTS_UNPC_002_AnimBP_C;

}

