#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Q110394_Reverse

#include "Basic.hpp"

#include "BP_AIRefreshConditionBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Q110394_Reverse.Q110394_Reverse_C
// 0x0000 (0x0048 - 0x0048)
class UQ110394_Reverse_C final : public UBP_AIRefreshConditionBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Q110394_Reverse_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Q110394_Reverse_C")
	}
	static class UQ110394_Reverse_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQ110394_Reverse_C>();
	}
};
DUMPER7_ASSERTS_UQ110394_Reverse_C;

}

