#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SprayFog

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class SprayFog.SprayVolumeFog
// 0x0068 (0x0330 - 0x02C8)
class ASprayVolumeFog final : public AActor
{
public:
	class UStaticMeshComponent*                   StaticMeshComponent;                               // 0x02C8(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UExponentialHeightFogComponent> HeightFog;                                  // 0x02D0(0x0028)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, InstancedReference, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInterface*                     FogMaterial;                                       // 0x02F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInterface*                     RayMarchingFogMaterial;                            // 0x0300(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             FogMap;                                            // 0x0308(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             FlowMap;                                           // 0x0310(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FogMapSize;                                        // 0x0318(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FogRange;                                          // 0x031C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstanceDynamic*               FogDIM;                                            // 0x0320(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstanceDynamic*               RaymachingFogDIM;                                  // 0x0328(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SprayVolumeFog")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SprayVolumeFog")
	}
	static class ASprayVolumeFog* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASprayVolumeFog>();
	}
};
DUMPER7_ASSERTS_ASprayVolumeFog;

}

