#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Swim_AnimInterface

#include "Basic.hpp"

#include "Swim_AnimInterface_classes.hpp"
#include "Swim_AnimInterface_parameters.hpp"


namespace SDK
{

// Function Swim_AnimInterface.Swim_AnimInterface_C.Swim
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       Swim_0                                                 (Parm, OutParm, NoDestructor)

void ISwim_AnimInterface_C::Swim(struct FPoseLink* Swim_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("Swim_AnimInterface_C", "Swim");

	Params::Swim_AnimInterface_C_Swim Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Swim_0 != nullptr)
		*Swim_0 = std::move(Parms.Swim_0);
}

}

