#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_HTButton_MainFormFunction_Mobile

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "HTGame_structs.hpp"
#include "HTGame_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_HTButton_MainFormFunction_Mobile.W_HTButton_MainFormFunction_Mobile_C
// 0x0310 (0x1E30 - 0x1B20)
class UW_HTButton_MainFormFunction_Mobile_C final : public UHTUI_Button
{
public:
	uint8                                         Pad_1B18[0x8];                                     // 0x1B18(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1B20(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_Yz;                                          // 0x1B28(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                ButtonBorder;                                      // 0x1B30(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       LoopAnim;                                          // 0x1B38(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	double                                        TextLeftRightPadding;                              // 0x1B40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        HitTestPadding_X;                                  // 0x1B48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        HitTestPadding_Y;                                  // 0x1B50(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        PressProgress;                                     // 0x1B58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateFontInfo                         Font;                                              // 0x1B60(0x0060)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSlateBrush                            ButtonBorderBrush;                                 // 0x1BC0(0x00B0)(Edit, BlueprintVisible)
	struct FSlateBrush                            IconBrush;                                         // 0x1C70(0x00B0)(Edit, BlueprintVisible)
	ETextTransformPolicy                          TextCase;                                          // 0x1D20(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          FlipIconXDimension;                                // 0x1D21(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsDisabled;                                        // 0x1D22(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UseImageOverlays;                                  // 0x1D23(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UseScaleChangeSpacers;                             // 0x1D24(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UseIconOverride;                                   // 0x1D25(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHorizontalAlignment                          InputHorzAlignment;                                // 0x1D26(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EVerticalAlignment                            InputVertAlignment;                                // 0x1D27(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                InputPadding;                                      // 0x1D28(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector2D                              ShadowOffset;                                      // 0x1D38(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           ShadowColorAndOpacity;                             // 0x1D48(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 TextStyle;                                         // 0x1D58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          UseYzBrush;                                        // 0x1D60(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D61[0xF];                                     // 0x1D61(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            YzBrush;                                           // 0x1D70(0x00B0)(Edit, BlueprintVisible)
	TArray<struct FStaticGuideWidgetInfo>         In_Guide_Infos;                                    // 0x1E20(0x0010)(Edit, BlueprintVisible)

public:
	class UTexture2D* BP_GetNormalPhoto();
	void BP_OnButtonLockedChanged(bool bNewLockedState);
	void BP_OnDisabled();
	void BP_OnEnabled();
	void ExecuteUbergraph_W_HTButton_MainFormFunction_Mobile(int32 EntryPoint);
	void GetPressProgress(double* Progress);
	void PreConstruct(bool IsDesignTime);
	void ResetMaterials();
	void SetBrush(const struct FSlateBrush& InBrush, struct FSlateBrush& CurBrush);
	void UpdateButtonStyles();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_HTButton_MainFormFunction_Mobile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_HTButton_MainFormFunction_Mobile_C")
	}
	static class UW_HTButton_MainFormFunction_Mobile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_HTButton_MainFormFunction_Mobile_C>();
	}
};
DUMPER7_ASSERTS_UW_HTButton_MainFormFunction_Mobile_C;

}

