#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_GamepadMainForm

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_GamepadMainForm.WB_GamepadMainForm_C
// 0x0000 (0x0630 - 0x0630)
class UWB_GamepadMainForm_C final : public UHTUI_GamepadMainForm
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WB_GamepadMainForm_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WB_GamepadMainForm_C")
	}
	static class UWB_GamepadMainForm_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_GamepadMainForm_C>();
	}
};
DUMPER7_ASSERTS_UWB_GamepadMainForm_C;

}

