#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WindowsPreload_BigWorld

#include "Basic.hpp"

#include "PlatformPreloadAssetsBP_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WindowsPreload_BigWorld.WindowsPreload_BigWorld_C
// 0x0000 (0x0048 - 0x0048)
class UWindowsPreload_BigWorld_C final : public UPlatformPreloadAssetsBP_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WindowsPreload_BigWorld_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WindowsPreload_BigWorld_C")
	}
	static class UWindowsPreload_BigWorld_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWindowsPreload_BigWorld_C>();
	}
};
DUMPER7_ASSERTS_UWindowsPreload_BigWorld_C;

}

