#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Actor_Adler_SkillDisplay2

#include "Basic.hpp"

#include "Actor_Adler_SkillDisplay2_classes.hpp"
#include "Actor_Adler_SkillDisplay2_parameters.hpp"


namespace SDK
{

// Function Actor_Adler_SkillDisplay2.Actor_Adler_SkillDisplay2_C.ExecuteUbergraph_Actor_Adler_SkillDisplay2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AActor_Adler_SkillDisplay2_C::ExecuteUbergraph_Actor_Adler_SkillDisplay2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Actor_Adler_SkillDisplay2_C", "ExecuteUbergraph_Actor_Adler_SkillDisplay2");

	Params::Actor_Adler_SkillDisplay2_C_ExecuteUbergraph_Actor_Adler_SkillDisplay2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Actor_Adler_SkillDisplay2.Actor_Adler_SkillDisplay2_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AActor_Adler_SkillDisplay2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Actor_Adler_SkillDisplay2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

