#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: boss_01_BP

#include "Basic.hpp"

#include "boss_01_BP_classes.hpp"
#include "boss_01_BP_parameters.hpp"


namespace SDK
{

// Function boss_01_BP.boss_01_BP_C.BP_AnimShowHuakuang
// (BlueprintCallable, BlueprintEvent)

void Aboss_01_BP_C::BP_AnimShowHuakuang()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "BP_AnimShowHuakuang");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.BP_OnArmorBroken
// (Event, Public, BlueprintEvent)

void Aboss_01_BP_C::BP_OnArmorBroken()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "BP_OnArmorBroken");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.BPOnAIActivated
// (Event, Public, BlueprintEvent)

void Aboss_01_BP_C::BPOnAIActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "BPOnAIActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.BPOnAICharacterDead
// (Event, Public, BlueprintEvent)

void Aboss_01_BP_C::BPOnAICharacterDead()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "BPOnAICharacterDead");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.BPOnBronAnim
// (Event, Public, BlueprintEvent)

void Aboss_01_BP_C::BPOnBronAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "BPOnBronAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.ChangeStageFromSkillBP
// (BlueprintCallable, BlueprintEvent)

void Aboss_01_BP_C::ChangeStageFromSkillBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "ChangeStageFromSkillBP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.Completed_1DE133124116D2D973C2C5B29320A5C2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ALevelSequenceActor*              LevelSequenceActor                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class ULevelSequencePlayer*             LevelSequencePlayer                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Aboss_01_BP_C::Completed_1DE133124116D2D973C2C5B29320A5C2(class ALevelSequenceActor* LevelSequenceActor, class ULevelSequencePlayer* LevelSequencePlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "Completed_1DE133124116D2D973C2C5B29320A5C2");

	Params::boss_01_BP_C_Completed_1DE133124116D2D973C2C5B29320A5C2 Parms{};

	Parms.LevelSequenceActor = LevelSequenceActor;
	Parms.LevelSequencePlayer = LevelSequencePlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function boss_01_BP.boss_01_BP_C.DeadSkillRotation
// (BlueprintCallable, BlueprintEvent)

void Aboss_01_BP_C::DeadSkillRotation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "DeadSkillRotation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.DissolveColor
// (BlueprintCallable, BlueprintEvent)

void Aboss_01_BP_C::DissolveColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "DissolveColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.ExecuteUbergraph_boss_01_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Aboss_01_BP_C::ExecuteUbergraph_boss_01_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "ExecuteUbergraph_boss_01_BP");

	Params::boss_01_BP_C_ExecuteUbergraph_boss_01_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function boss_01_BP.boss_01_BP_C.MoveBossToLocation
// (BlueprintCallable, BlueprintEvent)

void Aboss_01_BP_C::MoveBossToLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "MoveBossToLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void Aboss_01_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Aboss_01_BP_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "ReceiveEndPlay");

	Params::boss_01_BP_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function boss_01_BP.boss_01_BP_C.RecoverColor
// (BlueprintCallable, BlueprintEvent)

void Aboss_01_BP_C::RecoverColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "RecoverColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.Skl1BeginChange
// (BlueprintCallable, BlueprintEvent)

void Aboss_01_BP_C::Skl1BeginChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "Skl1BeginChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.Skl9BeginChange
// (BlueprintCallable, BlueprintEvent)

void Aboss_01_BP_C::Skl9BeginChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "Skl9BeginChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.时间轴_0__FinishedFunc
// (BlueprintEvent)

void Aboss_01_BP_C::时间轴_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "时间轴_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.时间轴_0__UpdateFunc
// (BlueprintEvent)

void Aboss_01_BP_C::时间轴_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "时间轴_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.时间轴_1__FinishedFunc
// (BlueprintEvent)

void Aboss_01_BP_C::时间轴_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "时间轴_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.时间轴_1__OFF_Light__EventFunc
// (BlueprintEvent)

void Aboss_01_BP_C::时间轴_1__OFF_Light__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "时间轴_1__OFF_Light__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.时间轴_1__UpdateFunc
// (BlueprintEvent)

void Aboss_01_BP_C::时间轴_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "时间轴_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.时间轴__FinishedFunc
// (BlueprintEvent)

void Aboss_01_BP_C::时间轴__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "时间轴__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function boss_01_BP.boss_01_BP_C.时间轴__UpdateFunc
// (BlueprintEvent)

void Aboss_01_BP_C::时间轴__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("boss_01_BP_C", "时间轴__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

