#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: boss_019_bullet_Skill08a_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "BP_ProjectileBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass boss_019_bullet_Skill08a_BP.boss_019_bullet_Skill08a_BP_C
// 0x0070 (0x0800 - 0x0790)
class Aboss_019_bullet_Skill08a_BP_C : public ABP_ProjectileBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0790(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHTNiagaraComponent*                    HTNiagara;                                         // 0x0798(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          BoxTriggerLinkTime;                                // 0x07A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         ____0______0_E4A0B3A14EBEF62FC817AE8E6F1D0078;     // 0x07A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            ____0__Direction_E4A0B3A14EBEF62FC817AE8E6F1D0078; // 0x07AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7AD[0x3];                                      // 0x07AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     时间轴_0;                                          // 0x07B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         _________0_8C483DEA47640180B95DDAAF832CB393;       // 0x07B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            _____Direction_8C483DEA47640180B95DDAAF832CB393;   // 0x07BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7BD[0x3];                                      // 0x07BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     时间轴;                                            // 0x07C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         DelaySetSpeed;                                     // 0x07C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7CC[0x4];                                      // 0x07CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 Current_Aggro_Target;                              // 0x07D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	double                                        Speed;                                             // 0x07D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                NewVar;                                            // 0x07E0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DelayActivate;                                     // 0x07F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_boss_019_bullet_Skill08a_BP(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveHit(class UPrimitiveComponent* MyComp, class AActor* Other, class UPrimitiveComponent* OtherComp, bool bSelfMoved, const struct FVector& HitLocation, const struct FVector& HitNormal, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	void 时间轴_0__FinishedFunc();
	void 时间轴_0__UpdateFunc();
	void 时间轴__FinishedFunc();
	void 时间轴__UpdateFunc();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("boss_019_bullet_Skill08a_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"boss_019_bullet_Skill08a_BP_C")
	}
	static class Aboss_019_bullet_Skill08a_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Aboss_019_bullet_Skill08a_BP_C>();
	}
};
DUMPER7_ASSERTS_Aboss_019_bullet_Skill08a_BP_C;

}

