#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BigWorldWater

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BE_WaterPlane_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BigWorldWater.BP_BigWorldWater_C
// 0x00C0 (0x0388 - 0x02C8)
class ABP_BigWorldWater_C final : public AHTBigWorldWaterPlane
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   WaterPlane;                                        // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UMaterialInterface>      PCWaterMaterial;                                   // 0x02E0(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftObjectPtr<class UMaterialInterface>      MobileWaterMaterial;                               // 0x0308(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftObjectPtr<class UStaticMesh>             MeshToLoad;                                        // 0x0330(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	EBE_WaterPlane                                PlaneDensity;                                      // 0x0358(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UseCustomMesh;                                     // 0x0359(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35A[0x6];                                      // 0x035A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UStaticMesh>             CustomMesh;                                        // 0x0360(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void UpdateRT();
	void ReceiveBeginPlay();
	void PreviewChange();
	void OnLoaded_7F59DBDA4A8103152ADBDB8DFDB4FBF5(class UObject* Loaded);
	void OnLoaded_4561F992483AC0AB74E06B928A4E17A1(class UObject* Loaded);
	void OnLoaded_41C07BCC42DA024D6EC6E89BFDAC814F(class UObject* Loaded);
	void LoadMobileWaterPlane(EBE_WaterPlane NewParam);
	void LoadMaterial();
	void ExecuteUbergraph_BP_BigWorldWater(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BigWorldWater_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BigWorldWater_C")
	}
	static class ABP_BigWorldWater_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BigWorldWater_C>();
	}
};
DUMPER7_ASSERTS_ABP_BigWorldWater_C;

}

