#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Dialogue

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Dialogue.BP_Dialogue_C
// 0x0000 (0x0140 - 0x0140)
class UBP_Dialogue_C final : public UHTRichTextBlockImageDecorator
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Dialogue_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Dialogue_C")
	}
	static class UBP_Dialogue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Dialogue_C>();
	}
};
DUMPER7_ASSERTS_UBP_Dialogue_C;

}

