#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Guide10005

#include "Basic.hpp"

#include "UINavigation_structs.hpp"
#include "Engine_structs.hpp"
#include "HTGame_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Guide10005.BP_Guide10005_C
// 0x0018 (0x0B98 - 0x0B80)
class ABP_Guide10005_C final : public AHTVisualActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0B80(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Box;                                               // 0x0B88(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class FName                                   Guide10005;                                        // 0x0B90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_Guide10005_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void ExecuteUbergraph_BP_Guide10005(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Guide10005_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Guide10005_C")
	}
	static class ABP_Guide10005_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Guide10005_C>();
	}
};
DUMPER7_ASSERTS_ABP_Guide10005_C;

}

