#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HoldStickWalk

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HoldStickWalk.BP_HoldStickWalk_C
// 0x0000 (0x00F8 - 0x00F8)
class UBP_HoldStickWalk_C final : public UHTCharacterCommonStateBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_HoldStickWalk_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_HoldStickWalk_C")
	}
	static class UBP_HoldStickWalk_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_HoldStickWalk_C>();
	}
};
DUMPER7_ASSERTS_UBP_HoldStickWalk_C;

}

