#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IdleState_BoxingNPC

#include "Basic.hpp"

#include "NPC_Sub_mm_IdleState_Fear_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IdleState_BoxingNPC.BP_IdleState_BoxingNPC_C
// 0x0000 (0x0360 - 0x0360)
class UBP_IdleState_BoxingNPC_C final : public UNPC_Sub_mm_IdleState_Fear_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_IdleState_BoxingNPC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_IdleState_BoxingNPC_C")
	}
	static class UBP_IdleState_BoxingNPC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_IdleState_BoxingNPC_C>();
	}
};
DUMPER7_ASSERTS_UBP_IdleState_BoxingNPC_C;

}

