#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NotifyState_DirBlur

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NotifyState_DirBlur.BP_NotifyState_DirBlur_C
// 0x0000 (0x01A0 - 0x01A0)
class UBP_NotifyState_DirBlur_C final : public UAnimNotifyState_DirBlur
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NotifyState_DirBlur_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NotifyState_DirBlur_C")
	}
	static class UBP_NotifyState_DirBlur_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NotifyState_DirBlur_C>();
	}
};
DUMPER7_ASSERTS_UBP_NotifyState_DirBlur_C;

}

