#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_Sub_mm

#include "Basic.hpp"

#include "BP_NPC_Sub_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NPC_Sub_mm.BP_NPC_Sub_mm_C
// 0x0000 (0x32C0 - 0x32C0)
#pragma pack(push, 0x1)
class alignas(0x10) ABP_NPC_Sub_mm_C : public ABP_NPC_Sub_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NPC_Sub_mm_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NPC_Sub_mm_C")
	}
	static class ABP_NPC_Sub_mm_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_Sub_mm_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_ABP_NPC_Sub_mm_C;

}

