#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_020_A_Tail

#include "Basic.hpp"

#include "BP_NPC_020_A_Tail_classes.hpp"
#include "BP_NPC_020_A_Tail_parameters.hpp"


namespace SDK
{

// Function BP_NPC_020_A_Tail.BP_NPC_020_A_Tail_C.ExecuteUbergraph_BP_NPC_020_A_Tail
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NPC_020_A_Tail_C::ExecuteUbergraph_BP_NPC_020_A_Tail(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_020_A_Tail_C", "ExecuteUbergraph_BP_NPC_020_A_Tail");

	Params::BP_NPC_020_A_Tail_C_ExecuteUbergraph_BP_NPC_020_A_Tail Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_NPC_020_A_Tail.BP_NPC_020_A_Tail_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_NPC_020_A_Tail_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_020_A_Tail_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

