#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_Mass_mm_Sub_B_battle

#include "Basic.hpp"

#include "BP_NPC_Mass_mm_Low_Battle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NPC_Mass_mm_Sub_B_battle.BP_NPC_Mass_mm_Sub_B_battle_C
// 0x0000 (0x2D40 - 0x2D40)
class ABP_NPC_Mass_mm_Sub_B_battle_C final : public ABP_NPC_Mass_mm_Low_Battle_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NPC_Mass_mm_Sub_B_battle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NPC_Mass_mm_Sub_B_battle_C")
	}
	static class ABP_NPC_Mass_mm_Sub_B_battle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_Mass_mm_Sub_B_battle_C>();
	}
};
DUMPER7_ASSERTS_ABP_NPC_Mass_mm_Sub_B_battle_C;

}

