#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerGlitchStencil_NotifyState

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlayerGlitchStencil_NotifyState.BP_PlayerGlitchStencil_NotifyState_C
// 0x0000 (0x0078 - 0x0078)
class UBP_PlayerGlitchStencil_NotifyState_C final : public UAnimNotifyState_PostEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlayerGlitchStencil_NotifyState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlayerGlitchStencil_NotifyState_C")
	}
	static class UBP_PlayerGlitchStencil_NotifyState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PlayerGlitchStencil_NotifyState_C>();
	}
};
DUMPER7_ASSERTS_UBP_PlayerGlitchStencil_NotifyState_C;

}

