#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RainMaskBoxComponet

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RainMaskBoxComponet.BP_RainMaskBoxComponet_C
// 0x0000 (0x0580 - 0x0580)
class UBP_RainMaskBoxComponet_C final : public URainMaxBoxComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RainMaskBoxComponet_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RainMaskBoxComponet_C")
	}
	static class UBP_RainMaskBoxComponet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_RainMaskBoxComponet_C>();
	}
};
DUMPER7_ASSERTS_UBP_RainMaskBoxComponet_C;

}

