#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RotateWithTheCamera

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RotateWithTheCamera.BP_RotateWithTheCamera_C
// 0x0000 (0x0030 - 0x0030)
class UBP_RotateWithTheCamera_C final : public UAnimNotifyState
{
public:
	bool Received_NotifyBegin(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float TotalDuration, const struct FAnimNotifyEventReference& EventReference) const;
	bool Received_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, const struct FAnimNotifyEventReference& EventReference) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RotateWithTheCamera_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RotateWithTheCamera_C")
	}
	static class UBP_RotateWithTheCamera_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_RotateWithTheCamera_C>();
	}
};
DUMPER7_ASSERTS_UBP_RotateWithTheCamera_C;

}

