#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SMC_PlaneOutline

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SMC_PlaneOutline.BP_SMC_PlaneOutline_C
// 0x0010 (0x0650 - 0x0640)
class UBP_SMC_PlaneOutline_C final : public UStaticMeshComponent
{
public:
	uint8                                         Pad_638[0x8];                                      // 0x0638(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0640(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_SMC_PlaneOutline(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SMC_PlaneOutline_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SMC_PlaneOutline_C")
	}
	static class UBP_SMC_PlaneOutline_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SMC_PlaneOutline_C>();
	}
};
DUMPER7_ASSERTS_UBP_SMC_PlaneOutline_C;

}

