#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TriggerSequencePlayer

#include "Basic.hpp"

#include "BP_TriggerSequencePlayer_classes.hpp"
#include "BP_TriggerSequencePlayer_parameters.hpp"


namespace SDK
{

// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.StopSequence
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ToStart_                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TriggerSequencePlayer_C::StopSequence(bool ToStart_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "StopSequence");

	Params::BP_TriggerSequencePlayer_C_StopSequence Parms{};

	Parms.ToStart_ = ToStart_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.ResetSequencePlayer
// (BlueprintCallable, BlueprintEvent)

void ABP_TriggerSequencePlayer_C::ResetSequencePlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "ResetSequencePlayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TriggerSequencePlayer_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "ReceiveEndPlay");

	Params::BP_TriggerSequencePlayer_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.PlaySequence
// (BlueprintCallable, BlueprintEvent)

void ABP_TriggerSequencePlayer_C::PlaySequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "PlaySequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.JumpToEnd
// (BlueprintCallable, BlueprintEvent)

void ABP_TriggerSequencePlayer_C::JumpToEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "JumpToEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.JumpTo
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  ToSubFrame                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ToFrameNumber                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TriggerSequencePlayer_C::JumpTo(double ToSubFrame, int32 ToFrameNumber, double Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "JumpTo");

	Params::BP_TriggerSequencePlayer_C_JumpTo Parms{};

	Parms.ToSubFrame = ToSubFrame;
	Parms.ToFrameNumber = ToFrameNumber;
	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.FromFrameTo
// (BlueprintCallable, BlueprintEvent)

void ABP_TriggerSequencePlayer_C::FromFrameTo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "FromFrameTo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.FinishStopPlaying
// (BlueprintCallable, BlueprintEvent)

void ABP_TriggerSequencePlayer_C::FinishStopPlaying()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "FinishStopPlaying");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.ExecuteUbergraph_BP_TriggerSequencePlayer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TriggerSequencePlayer_C::ExecuteUbergraph_BP_TriggerSequencePlayer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "ExecuteUbergraph_BP_TriggerSequencePlayer");

	Params::BP_TriggerSequencePlayer_C_ExecuteUbergraph_BP_TriggerSequencePlayer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.EndDestroy
// (BlueprintCallable, BlueprintEvent)

void ABP_TriggerSequencePlayer_C::EndDestroy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "EndDestroy");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.Completed_E284F72344C4C51B2AA45BAA838840D0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ALevelSequenceActor*              LevelSequenceActor                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class ULevelSequencePlayer*             LevelSequencePlayer                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_TriggerSequencePlayer_C::Completed_E284F72344C4C51B2AA45BAA838840D0(class ALevelSequenceActor* LevelSequenceActor, class ULevelSequencePlayer* LevelSequencePlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "Completed_E284F72344C4C51B2AA45BAA838840D0");

	Params::BP_TriggerSequencePlayer_C_Completed_E284F72344C4C51B2AA45BAA838840D0 Parms{};

	Parms.LevelSequenceActor = LevelSequenceActor;
	Parms.LevelSequencePlayer = LevelSequencePlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.Completed_851A67A34D2962400F547A91DA4D73CD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ALevelSequenceActor*              LevelSequenceActor                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class ULevelSequencePlayer*             LevelSequencePlayer                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_TriggerSequencePlayer_C::Completed_851A67A34D2962400F547A91DA4D73CD(class ALevelSequenceActor* LevelSequenceActor, class ULevelSequencePlayer* LevelSequencePlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "Completed_851A67A34D2962400F547A91DA4D73CD");

	Params::BP_TriggerSequencePlayer_C_Completed_851A67A34D2962400F547A91DA4D73CD Parms{};

	Parms.LevelSequenceActor = LevelSequenceActor;
	Parms.LevelSequencePlayer = LevelSequencePlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.Completed_4F84CBC948E8E59A59041AA68A08EA76
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ALevelSequenceActor*              LevelSequenceActor                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class ULevelSequencePlayer*             LevelSequencePlayer                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_TriggerSequencePlayer_C::Completed_4F84CBC948E8E59A59041AA68A08EA76(class ALevelSequenceActor* LevelSequenceActor, class ULevelSequencePlayer* LevelSequencePlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "Completed_4F84CBC948E8E59A59041AA68A08EA76");

	Params::BP_TriggerSequencePlayer_C_Completed_4F84CBC948E8E59A59041AA68A08EA76 Parms{};

	Parms.LevelSequenceActor = LevelSequenceActor;
	Parms.LevelSequencePlayer = LevelSequencePlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.ChangeCollision
// (BlueprintCallable, BlueprintEvent)

void ABP_TriggerSequencePlayer_C::ChangeCollision()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "ChangeCollision");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.BPOnMainRoleLoadFinished
// (Event, Public, BlueprintEvent)
// Parameters:
// class AHTPlayerState*                   PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_TriggerSequencePlayer_C::BPOnMainRoleLoadFinished(class AHTPlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "BPOnMainRoleLoadFinished");

	Params::BP_TriggerSequencePlayer_C_BPOnMainRoleLoadFinished Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TriggerSequencePlayer.BP_TriggerSequencePlayer_C.BndEvt__BP_TriggerSequencePlayer_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_TriggerSequencePlayer_C::BndEvt__BP_TriggerSequencePlayer_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TriggerSequencePlayer_C", "BndEvt__BP_TriggerSequencePlayer_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_TriggerSequencePlayer_C_BndEvt__BP_TriggerSequencePlayer_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}

}

