#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Vehicle_006_ModuleTraffic

#include "Basic.hpp"

#include "BP_Vehicle_006_ModuleTraffic_classes.hpp"
#include "BP_Vehicle_006_ModuleTraffic_parameters.hpp"


namespace SDK
{

// Function BP_Vehicle_006_ModuleTraffic.BP_Vehicle_006_ModuleTraffic_C.ExecuteUbergraph_BP_Vehicle_006_ModuleTraffic
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Vehicle_006_ModuleTraffic_C::ExecuteUbergraph_BP_Vehicle_006_ModuleTraffic(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vehicle_006_ModuleTraffic_C", "ExecuteUbergraph_BP_Vehicle_006_ModuleTraffic");

	Params::BP_Vehicle_006_ModuleTraffic_C_ExecuteUbergraph_BP_Vehicle_006_ModuleTraffic Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vehicle_006_ModuleTraffic.BP_Vehicle_006_ModuleTraffic_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Vehicle_006_ModuleTraffic_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vehicle_006_ModuleTraffic_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

