#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Vehicle_005_Low

#include "Basic.hpp"

#include "BP_Vehicle_005_Low_classes.hpp"
#include "BP_Vehicle_005_Low_parameters.hpp"


namespace SDK
{

// Function BP_Vehicle_005_Low.BP_Vehicle_005_Low_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Vehicle_005_Low_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vehicle_005_Low_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

