#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WorldBoss_Exit_Boss019

#include "Basic.hpp"

#include "BP_WorldBoss_Exit_Boss019_classes.hpp"
#include "BP_WorldBoss_Exit_Boss019_parameters.hpp"


namespace SDK
{

// Function BP_WorldBoss_Exit_Boss019.BP_WorldBoss_Exit_Boss019_C.BndEvt__BP_WorldBoss_Exit_Boss019_TriggerComponent_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_WorldBoss_Exit_Boss019_C::BndEvt__BP_WorldBoss_Exit_Boss019_TriggerComponent_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WorldBoss_Exit_Boss019_C", "BndEvt__BP_WorldBoss_Exit_Boss019_TriggerComponent_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");

	Params::BP_WorldBoss_Exit_Boss019_C_BndEvt__BP_WorldBoss_Exit_Boss019_TriggerComponent_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WorldBoss_Exit_Boss019.BP_WorldBoss_Exit_Boss019_C.BP_MonsterExitScene
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             InMonsterID                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_WorldBoss_Exit_Boss019_C::BP_MonsterExitScene(class FName InMonsterID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WorldBoss_Exit_Boss019_C", "BP_MonsterExitScene");

	Params::BP_WorldBoss_Exit_Boss019_C_BP_MonsterExitScene Parms{};

	Parms.InMonsterID = InMonsterID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WorldBoss_Exit_Boss019.BP_WorldBoss_Exit_Boss019_C.ExecuteUbergraph_BP_WorldBoss_Exit_Boss019
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_WorldBoss_Exit_Boss019_C::ExecuteUbergraph_BP_WorldBoss_Exit_Boss019(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WorldBoss_Exit_Boss019_C", "ExecuteUbergraph_BP_WorldBoss_Exit_Boss019");

	Params::BP_WorldBoss_Exit_Boss019_C_ExecuteUbergraph_BP_WorldBoss_Exit_Boss019 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

