#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFishingCursorActor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPFishingCursorActor.BPFishingCursorActor_C
// 0x0010 (0x0BB8 - 0x0BA8)
class ABPFishingCursorActor_C final : public AHTFishingCursorActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Cube;                                              // 0x0BB0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPFishingCursorActor(int32 EntryPoint);
	void SetCursorCanUsed(bool _use);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPFishingCursorActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPFishingCursorActor_C")
	}
	static class ABPFishingCursorActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPFishingCursorActor_C>();
	}
};
DUMPER7_ASSERTS_ABPFishingCursorActor_C;

}

