#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_FluxInteraction

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_FluxInteraction.BPI_FluxInteraction_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_FluxInteraction_C final
{
public:
	void GetInteractions(double Ratio, int32 Iteration, TArray<struct FBS_FluxInteractionData>* Interactions);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_FluxInteraction_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_FluxInteraction_C")
	}
	static class IBPI_FluxInteraction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_FluxInteraction_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_FluxInteraction_C;

}

