#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPL_FluidFlux

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPL_FluidFlux.BPL_FluidFlux_C
// 0x0000 (0x0028 - 0x0028)
class BPL_FluidFlux::UBPL_FluidFlux_C final : public UBlueprintFunctionLibrary
{
public:
	static void SmoothLerp(double A, double B, double Decay, double Delta, class UObject* __WorldContext, double* Result);
	static void SetTexture2DConfig(class UTexture2D* RenderTargetObject, ETextureFilter Filter, bool SRGB, ETextureAddress Address_X, ETextureAddress Address_Y, ETextureMipGenSettings Mip_Gen_Settings, class UObject* __WorldContext);
	static void SetRenderTargetConfig(class UTextureRenderTarget2D* RenderTargetObject, ETextureFilter Filter, bool SRGB, ETextureAddress Address_X, ETextureAddress Address_Y, class UObject* __WorldContext);
	static void SetRectTransform2D(class UMaterialInstanceDynamic*& Target, const struct FTransform& InTransform, class UObject* __WorldContext);
	static void RecreateRenderTarget(class UTextureRenderTarget2D* CurrentTexture, int32 Width, int32 Height, ETextureRenderTargetFormat Format, const struct FLinearColor& ClearColor, uint8 LOD, bool GenerateMipmaps, bool Clear, bool AllowResize, class UObject* __WorldContext, class UTextureRenderTarget2D** NewTexture);
	static void IsValuePowerOfTwo(int32 Value, class UObject* __WorldContext, bool* Result);
	static void IsPointPowerOfTwo(const struct FIntPoint& Value, class UObject* __WorldContext, bool* Result);
	static void GetUndefiniedHeight(class UObject* __WorldContext, double* NewParam);
	static void GetTextureResolution(class UTexture* Texture, class UObject* __WorldContext, struct FIntPoint* Size);
	static void GetEngineVersionInt(class UObject* __WorldContext, int32* Integer);
	static void FramesToTiles(int32 Frames, class UObject* __WorldContext, struct FIntPoint* Tiles);

	void MakeVolumeLocalTransform(const struct FVector& ExtraSize, const struct FVector& Scale, double ZOffsetScale, class UObject* __WorldContext, struct FTransform* Transform);

	void GetBordersVector(int32 StateAreaBorders, class UObject* __WorldContext, struct FLinearColor* LinearColor) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BPL_FluidFlux.BPL_FluidFlux_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPL_FluidFlux_C")
	}
	static class BPL_FluidFlux::UBPL_FluidFlux_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BPL_FluidFlux::UBPL_FluidFlux_C>();
	}
};
DUMPER7_ASSERTS_BPL_FluidFlux__UBPL_FluidFlux_C;

}

