#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPSwimmingBladderActor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_FishingActorBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPSwimmingBladderActor.BPSwimmingBladderActor_C
// 0x0010 (0x0780 - 0x0770)
class ABPSwimmingBladderActor_C final : public ABP_FishingActorBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BPSwimmingBladderActor_C;           // 0x0770(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      NS_Fishing_Fishhook_Spot;                          // 0x0778(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPSwimmingBladderActor(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPSwimmingBladderActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPSwimmingBladderActor_C")
	}
	static class ABPSwimmingBladderActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPSwimmingBladderActor_C>();
	}
};
DUMPER7_ASSERTS_ABPSwimmingBladderActor_C;

}

