#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_PianoPlayMain

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPUI_PianoPlayMain.BPUI_PianoPlayMain_C.BndEvt__BPUI_PianoPlayMain_W_HTButton_Close_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_PianoPlayMain_C_BndEvt__BPUI_PianoPlayMain_W_HTButton_Close_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_PianoPlayMain_C_BndEvt__BPUI_PianoPlayMain_W_HTButton_Close_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_PianoPlayMain.BPUI_PianoPlayMain_C.BndEvt__BPUI_PianoPlayMain_W_HTButton_Setting_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_PianoPlayMain_C_BndEvt__BPUI_PianoPlayMain_W_HTButton_Setting_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_PianoPlayMain_C_BndEvt__BPUI_PianoPlayMain_W_HTButton_Setting_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_PianoPlayMain.BPUI_PianoPlayMain_C.ExecuteUbergraph_BPUI_PianoPlayMain
// 0x0018 (0x0018 - 0x0000)
struct BPUI_PianoPlayMain_C_ExecuteUbergraph_BPUI_PianoPlayMain final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_1;               // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_PianoPlayMain_C_ExecuteUbergraph_BPUI_PianoPlayMain;

}

