#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_SetBackRotation

#include "Basic.hpp"

#include "BTTask_SetBackRotation_classes.hpp"
#include "BTTask_SetBackRotation_parameters.hpp"


namespace SDK
{

// Function BTTask_SetBackRotation.BTTask_SetBackRotation_C.ExecuteUbergraph_BTTask_SetBackRotation
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_SetBackRotation_C::ExecuteUbergraph_BTTask_SetBackRotation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_SetBackRotation_C", "ExecuteUbergraph_BTTask_SetBackRotation");

	Params::BTTask_SetBackRotation_C_ExecuteUbergraph_BTTask_SetBackRotation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_SetBackRotation.BTTask_SetBackRotation_C.ReceiveExecuteAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBTTask_SetBackRotation_C::ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_SetBackRotation_C", "ReceiveExecuteAI");

	Params::BTTask_SetBackRotation_C_ReceiveExecuteAI Parms{};

	Parms.OwnerController = OwnerController;
	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}

}

