#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Calc_Hathor_AngerActiveAtkUp

#include "Basic.hpp"

#include "BP_HTGameplayMMCalcBase_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Calc_Hathor_AngerActiveAtkUp.Calc_Hathor_AngerActiveAtkUp_C
// 0x0000 (0x0060 - 0x0060)
class UCalc_Hathor_AngerActiveAtkUp_C final : public UBP_HTGameplayMMCalcBase_C
{
public:
	float HTCustomCalculateBaseMagnitude(const class AActor* OwnerActor, const class AActor* HitActor, const class AActor* InstigatorActor) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Calc_Hathor_AngerActiveAtkUp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Calc_Hathor_AngerActiveAtkUp_C")
	}
	static class UCalc_Hathor_AngerActiveAtkUp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCalc_Hathor_AngerActiveAtkUp_C>();
	}
};
DUMPER7_ASSERTS_UCalc_Hathor_AngerActiveAtkUp_C;

}

