#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Camera_Mitsuki_UltralSkill1

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Camera_Mitsuki_UltralSkill1.Camera_Mitsuki_UltralSkill1_C
// 0x0000 (0x0CB0 - 0x0CB0)
class UCamera_Mitsuki_UltralSkill1_C final : public UHTCameraSettingModifier_General
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Camera_Mitsuki_UltralSkill1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Camera_Mitsuki_UltralSkill1_C")
	}
	static class UCamera_Mitsuki_UltralSkill1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCamera_Mitsuki_UltralSkill1_C>();
	}
};
DUMPER7_ASSERTS_UCamera_Mitsuki_UltralSkill1_C;

}

