#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cau_Wishwell_Punish

#include "Basic.hpp"

#include "BP_HTGameplayMMCalcBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cau_Wishwell_Punish.Cau_Wishwell_Punish_C
// 0x0010 (0x0070 - 0x0060)
class UCau_Wishwell_Punish_C final : public UBP_HTGameplayMMCalcBase_C
{
public:
	class AHTPlayerCharacter*                     As_HTPlayer_Character;                             // 0x0060(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UHTGATargetType>            Target_Type_Class;                                 // 0x0068(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	float HTCustomCalculateBaseMagnitude(const class AActor* OwnerActor, const class AActor* HitActor, const class AActor* InstigatorActor) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Cau_Wishwell_Punish_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cau_Wishwell_Punish_C")
	}
	static class UCau_Wishwell_Punish_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCau_Wishwell_Punish_C>();
	}
};
DUMPER7_ASSERTS_UCau_Wishwell_Punish_C;

}

