#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cau_Fadia_Q_RecoverHP

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "BP_HTGameplayMMCalcBase_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cau_Fadia_Q_RecoverHP.Cau_Fadia_Q_RecoverHP_C
// 0x0050 (0x00B0 - 0x0060)
class UCau_Fadia_Q_RecoverHP_C : public UBP_HTGameplayMMCalcBase_C
{
public:
	struct FScalableFloat                         AdditiveRecoverMulScalarFloatLv4;                  // 0x0060(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         RecoverMulScalarFloat;                             // 0x0088(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	float HTCustomCalculateBaseMagnitude(const class AActor* OwnerActor, const class AActor* HitActor, const class AActor* InstigatorActor) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Cau_Fadia_Q_RecoverHP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cau_Fadia_Q_RecoverHP_C")
	}
	static class UCau_Fadia_Q_RecoverHP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCau_Fadia_Q_RecoverHP_C>();
	}
};
DUMPER7_ASSERTS_UCau_Fadia_Q_RecoverHP_C;

}

