#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CloudsLighting

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "CloudsLighting_structs.hpp"


namespace SDK
{

// Class CloudsLighting.CloudsLightingSystem
// 0x0040 (0x0308 - 0x02C8)
class ACloudsLightingSystem final : public AActor
{
public:
	class UTextureRenderTarget2D*                 UserLightDataMap;                                  // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Group;                                             // 0x02D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2D4[0x4];                                      // 0x02D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        RootSceneComponent;                                // 0x02D8(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UTextureRenderTarget2D*                 LightDataMap;                                      // 0x02E0(0x0008)(ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UTextureRenderTarget2D*                 DefaultLightDataMap;                               // 0x02E8(0x0008)(ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UTextureRenderTarget2D*                 CurrentUserLightDataMap;                           // 0x02F0(0x0008)(ZeroConstructor, Transient, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_2F8[0x10];                                     // 0x02F8(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool IsValid();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CloudsLightingSystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CloudsLightingSystem")
	}
	static class ACloudsLightingSystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACloudsLightingSystem>();
	}
};
DUMPER7_ASSERTS_ACloudsLightingSystem;

// Class CloudsLighting.VolumetricLightSource
// 0x0030 (0x02F8 - 0x02C8)
class AVolumetricLightSource : public AActor
{
public:
	EVLightSourceType                             LightSourceType;                                   // 0x02C8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C9[0x3];                                      // 0x02C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Group;                                             // 0x02CC(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           Color1;                                            // 0x02D0(0x0010)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           Color2;                                            // 0x02E0(0x0010)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Range;                                             // 0x02F0(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Softness;                                          // 0x02F4(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	EVLightSourceType GetType() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("VolumetricLightSource")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VolumetricLightSource")
	}
	static class AVolumetricLightSource* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVolumetricLightSource>();
	}
};
DUMPER7_ASSERTS_AVolumetricLightSource;

// Class CloudsLighting.VolumetricPointLight
// 0x0000 (0x02F8 - 0x02F8)
class AVolumetricPointLight final : public AVolumetricLightSource
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("VolumetricPointLight")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VolumetricPointLight")
	}
	static class AVolumetricPointLight* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVolumetricPointLight>();
	}
};
DUMPER7_ASSERTS_AVolumetricPointLight;

// Class CloudsLighting.VolumetricSpotLight
// 0x0018 (0x0310 - 0x02F8)
class AVolumetricSpotLight final : public AVolumetricLightSource
{
public:
	float                                         SourceLength;                                      // 0x02F8(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SourceRadius;                                      // 0x02FC(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CutDistance;                                       // 0x0300(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AngFalloffMult;                                    // 0x0304(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, Interp, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 LineColor;                                         // 0x0308(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         LineThickness;                                     // 0x030C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("VolumetricSpotLight")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VolumetricSpotLight")
	}
	static class AVolumetricSpotLight* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVolumetricSpotLight>();
	}
};
DUMPER7_ASSERTS_AVolumetricSpotLight;

}

