#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Con_Hathor_AngerActive_AtkUp_Del

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Con_Hathor_AngerActive_AtkUp_Del.Con_Hathor_AngerActive_AtkUp_Del_C
// 0x0000 (0x0030 - 0x0030)
class UCon_Hathor_AngerActive_AtkUp_Del_C final : public UHTGameplayEffectCustomApplicationRequirement
{
public:
	bool CanApplyGameplayEffectContent(class AActor* SourceActor, class AActor* TargetActor, class AActor* InstigatorActor, const class UGameplayEffect* GameplayEffect) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Con_Hathor_AngerActive_AtkUp_Del_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Con_Hathor_AngerActive_AtkUp_Del_C")
	}
	static class UCon_Hathor_AngerActive_AtkUp_Del_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCon_Hathor_AngerActive_AtkUp_Del_C>();
	}
};
DUMPER7_ASSERTS_UCon_Hathor_AngerActive_AtkUp_Del_C;

}

