#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Controller_Boss_017

#include "Basic.hpp"

#include "MonsterControllerBP_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Controller_Boss_017.Controller_Boss_017_C
// 0x0000 (0x08B0 - 0x08B0)
class AController_Boss_017_C final : public AMonsterControllerBP_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Controller_Boss_017_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Controller_Boss_017_C")
	}
	static class AController_Boss_017_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AController_Boss_017_C>();
	}
};
DUMPER7_ASSERTS_AController_Boss_017_C;

}

