#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CriWareWindowsSettings

#include "Basic.hpp"

#include "CriWareWindowsSettings_structs.hpp"
#include "CriWareCore_structs.hpp"
#include "CriWareCore_classes.hpp"
#include "DeveloperSettings_classes.hpp"


namespace SDK
{

// Class CriWareWindowsSettings.AtomWindowsEndpointSettings
// 0x0008 (0x0030 - 0x0028)
class UAtomWindowsEndpointSettings final : public UAtomEndpointSettingsBase
{
public:
	bool                                          bOverrideHardwareDevice;                           // 0x0028(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAtomWindowsHardwareDevices                   HardwareDeviceOverrides;                           // 0x0029(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSendToVibrationOutput;                            // 0x002A(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2B[0x5];                                       // 0x002B(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AtomWindowsEndpointSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AtomWindowsEndpointSettings")
	}
	static class UAtomWindowsEndpointSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAtomWindowsEndpointSettings>();
	}
};
DUMPER7_ASSERTS_UAtomWindowsEndpointSettings;

// Class CriWareWindowsSettings.CriWareWindowsSettings
// 0x00A8 (0x00E0 - 0x0038)
class UCriWareWindowsSettings final : public UDeveloperSettings
{
public:
	struct FAtomVoicesSettings                    VoicesOverrides;                                   // 0x0038(0x000C)(Edit, Config, NoDestructor, NativeAccessSpecifierPublic)
	struct FCriWareWASAPISettings                 WASAPISettings;                                    // 0x0044(0x0014)(Edit, Config, NoDestructor, NativeAccessSpecifierPublic)
	class FName                                   EndpointMappings[0xA];                             // 0x0058(0x0008)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   Hardware1;                                         // 0x00A8(0x0008)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   Hardware2;                                         // 0x00B0(0x0008)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   Hardware3;                                         // 0x00B8(0x0008)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   Hardware4;                                         // 0x00C0(0x0008)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCriWareCookOverridesSettings          CookOverrides;                                     // 0x00C8(0x0002)(Edit, Config, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_CA[0x6];                                       // 0x00CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 AtomSourceDataOverridePlugin;                      // 0x00D0(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	TArray<class FString> GetHardwareDeviceOptions() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CriWareWindowsSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CriWareWindowsSettings")
	}
	static class UCriWareWindowsSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCriWareWindowsSettings>();
	}
};
DUMPER7_ASSERTS_UCriWareWindowsSettings;

}

