#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DamageActorLacrimosaUltraSkill

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_DamageTriggerActorBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DamageActorLacrimosaUltraSkill.DamageActorLacrimosaUltraSkill_C
// 0x0010 (0x05F8 - 0x05E8)
class ADamageActorLacrimosaUltraSkill_C final : public ABP_DamageTriggerActorBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UForceFieldInteractionComponent*        WindFieldInteraction;                              // 0x05F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_DamageActorLacrimosaUltraSkill(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DamageActorLacrimosaUltraSkill_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DamageActorLacrimosaUltraSkill_C")
	}
	static class ADamageActorLacrimosaUltraSkill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADamageActorLacrimosaUltraSkill_C>();
	}
};
DUMPER7_ASSERTS_ADamageActorLacrimosaUltraSkill_C;

}

