#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DamageActorMitsukiMelee4

#include "Basic.hpp"

#include "DamageActorMitsukiMelee4_classes.hpp"
#include "DamageActorMitsukiMelee4_parameters.hpp"


namespace SDK
{

// Function DamageActorMitsukiMelee4.DamageActorMitsukiMelee4_C.ExecuteUbergraph_DamageActorMitsukiMelee4
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADamageActorMitsukiMelee4_C::ExecuteUbergraph_DamageActorMitsukiMelee4(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DamageActorMitsukiMelee4_C", "ExecuteUbergraph_DamageActorMitsukiMelee4");

	Params::DamageActorMitsukiMelee4_C_ExecuteUbergraph_DamageActorMitsukiMelee4 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DamageActorMitsukiMelee4.DamageActorMitsukiMelee4_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ADamageActorMitsukiMelee4_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DamageActorMitsukiMelee4_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

