#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DamageRange_Lacrimosa_PerfectAtk

#include "Basic.hpp"

#include "BP_PlayerType_DamageSphereBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DamageRange_Lacrimosa_PerfectAtk.DamageRange_Lacrimosa_PerfectAtk_C
// 0x0000 (0x0110 - 0x0110)
class UDamageRange_Lacrimosa_PerfectAtk_C final : public UBP_PlayerType_DamageSphereBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DamageRange_Lacrimosa_PerfectAtk_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DamageRange_Lacrimosa_PerfectAtk_C")
	}
	static class UDamageRange_Lacrimosa_PerfectAtk_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDamageRange_Lacrimosa_PerfectAtk_C>();
	}
};
DUMPER7_ASSERTS_UDamageRange_Lacrimosa_PerfectAtk_C;

}

