#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Adler_Skill

#include "Basic.hpp"

#include "GA_Adler_Skill_classes.hpp"
#include "GA_Adler_Skill_parameters.hpp"


namespace SDK
{

// Function GA_Adler_Skill.GA_Adler_Skill_C.ExecuteUbergraph_GA_Adler_Skill
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Adler_Skill_C::ExecuteUbergraph_GA_Adler_Skill(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Adler_Skill_C", "ExecuteUbergraph_GA_Adler_Skill");

	Params::GA_Adler_Skill_C_ExecuteUbergraph_GA_Adler_Skill Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Adler_Skill.GA_Adler_Skill_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Adler_Skill_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Adler_Skill_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}

}

