#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Fadia_PerfectEvade

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_MeleeBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Fadia_PerfectEvade.GA_Fadia_PerfectEvade_C
// 0x0010 (0x0BD0 - 0x0BC0)
class UGA_Fadia_PerfectEvade_C final : public UGA_MeleeBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Fadia_PerfectEvade_C;            // 0x0BC0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void K2_ActivateAbility();
	void ExecuteUbergraph_GA_Fadia_PerfectEvade(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Fadia_PerfectEvade_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Fadia_PerfectEvade_C")
	}
	static class UGA_Fadia_PerfectEvade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Fadia_PerfectEvade_C>();
	}
};
DUMPER7_ASSERTS_UGA_Fadia_PerfectEvade_C;

}

