#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_mon_39_act03_Steal

#include "Basic.hpp"

#include "GA_SkillBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_mon_39_act03_Steal.GA_mon_39_act03_Steal_C
// 0x0000 (0x0BC0 - 0x0BC0)
class UGA_mon_39_act03_Steal_C final : public UGA_SkillBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_mon_39_act03_Steal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_mon_39_act03_Steal_C")
	}
	static class UGA_mon_39_act03_Steal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_mon_39_act03_Steal_C>();
	}
};
DUMPER7_ASSERTS_UGA_mon_39_act03_Steal_C;

}

