#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_mon_02_act02_Steal

#include "Basic.hpp"

#include "GA_mon_02_act02_Steal_classes.hpp"
#include "GA_mon_02_act02_Steal_parameters.hpp"


namespace SDK
{

// Function GA_mon_02_act02_Steal.GA_mon_02_act02_Steal_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_mon_02_act02_Steal_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_mon_02_act02_Steal_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_mon_02_act02_Steal.GA_mon_02_act02_Steal_C.ExecuteUbergraph_GA_mon_02_act02_Steal
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_mon_02_act02_Steal_C::ExecuteUbergraph_GA_mon_02_act02_Steal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_mon_02_act02_Steal_C", "ExecuteUbergraph_GA_mon_02_act02_Steal");

	Params::GA_mon_02_act02_Steal_C_ExecuteUbergraph_GA_mon_02_act02_Steal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

