#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Skia_ShadowEvadeEnd

#include "Basic.hpp"

#include "GA_Skia_ShadowEvadeEnd_classes.hpp"
#include "GA_Skia_ShadowEvadeEnd_parameters.hpp"


namespace SDK
{

// Function GA_Skia_ShadowEvadeEnd.GA_Skia_ShadowEvadeEnd_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Skia_ShadowEvadeEnd_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Skia_ShadowEvadeEnd_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Skia_ShadowEvadeEnd.GA_Skia_ShadowEvadeEnd_C.ExecuteUbergraph_GA_Skia_ShadowEvadeEnd
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Skia_ShadowEvadeEnd_C::ExecuteUbergraph_GA_Skia_ShadowEvadeEnd(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Skia_ShadowEvadeEnd_C", "ExecuteUbergraph_GA_Skia_ShadowEvadeEnd");

	Params::GA_Skia_ShadowEvadeEnd_C_ExecuteUbergraph_GA_Skia_ShadowEvadeEnd Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

