#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HierarchicalInstanced

#include "Basic.hpp"


namespace SDK
{

// Enum HierarchicalInstanced.EInstancedTargetAreaFlags
// NumValues: 0x0006
enum class EInstancedTargetAreaFlags : uint8
{
	All                                      = 0,
	SelectedLevel                            = 1,
	SelectedDataLayers                       = 2,
	OnlyVolume                               = 3,
	OnlyLoadedRegions                        = 4,
	EInstancedTargetAreaFlags_MAX            = 5,
};

}

