#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HitOut_boss019_Skill08c

#include "Basic.hpp"

#include "SkillEffect_HitOut_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HitOut_boss019_Skill08c.HitOut_boss019_Skill08c_C
// 0x0000 (0x01C0 - 0x01C0)
class UHitOut_boss019_Skill08c_C final : public USkillEffect_HitOut_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HitOut_boss019_Skill08c_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HitOut_boss019_Skill08c_C")
	}
	static class UHitOut_boss019_Skill08c_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHitOut_boss019_Skill08c_C>();
	}
};
DUMPER7_ASSERTS_UHitOut_boss019_Skill08c_C;

}

