#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LacrimosaUltraSkillHitOut

#include "Basic.hpp"

#include "SkillEffect_HitOut_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LacrimosaUltraSkillHitOut.LacrimosaUltraSkillHitOut_C
// 0x0000 (0x01C0 - 0x01C0)
class ULacrimosaUltraSkillHitOut_C final : public USkillEffect_HitOut_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LacrimosaUltraSkillHitOut_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LacrimosaUltraSkillHitOut_C")
	}
	static class ULacrimosaUltraSkillHitOut_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULacrimosaUltraSkillHitOut_C>();
	}
};
DUMPER7_ASSERTS_ULacrimosaUltraSkillHitOut_C;

}

