#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MB_Sadbear_Right

#include "Basic.hpp"


namespace SDK::Params
{

// Function MB_Sadbear_Right.MB_Sadbear_Right_C.Begin_move
// 0x0001 (0x0001 - 0x0000)
struct MB_Sadbear_Right_C_Begin_move final
{
public:
	bool                                          dayornight;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MB_Sadbear_Right_C_Begin_move;

// Function MB_Sadbear_Right.MB_Sadbear_Right_C.BPOnMainRoleLoadFinished
// 0x0008 (0x0008 - 0x0000)
struct MB_Sadbear_Right_C_BPOnMainRoleLoadFinished final
{
public:
	class AHTPlayerState*                         PlayerState;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MB_Sadbear_Right_C_BPOnMainRoleLoadFinished;

// Function MB_Sadbear_Right.MB_Sadbear_Right_C.ExecuteUbergraph_MB_Sadbear_Right
// 0x0010 (0x0010 - 0x0000)
struct MB_Sadbear_Right_C_ExecuteUbergraph_MB_Sadbear_Right final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_dayornight;                     // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AHTPlayerState*                         K2Node_Event_PlayerState;                          // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MB_Sadbear_Right_C_ExecuteUbergraph_MB_Sadbear_Right;

}

