#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: mon_38_AnimBP

#include "Basic.hpp"

#include "MonsterAnimBP_Base_structs.hpp"


namespace SDK
{

// ScriptStruct mon_38_AnimBP.mon_38_AnimBP_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x2960 - 0x2960)
struct mon_38_AnimBP::FAnimBlueprintGeneratedConstantData final : public MonsterAnimBP_Base::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_mon_38_AnimBP__FAnimBlueprintGeneratedConstantData;

}

