#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_007_AnimBP

#include "Basic.hpp"

#include "NPCAnimBP_Base_structs.hpp"


namespace SDK
{

// ScriptStruct NPC_007_AnimBP.NPC_007_AnimBP_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x1850 - 0x1850)
struct NPC_007_AnimBP::FAnimBlueprintGeneratedConstantData final : public NPCAnimBP_Base::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_NPC_007_AnimBP__FAnimBlueprintGeneratedConstantData;

}

