#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Sub_fl_Simple_sit_Base

#include "Basic.hpp"

#include "NPC_Sub_fl_Simple_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPC_Sub_fl_Simple_sit_Base.NPC_Sub_fl_Simple_sit_Base_C
// 0x0000 (0x07A0 - 0x07A0)
#pragma pack(push, 0x1)
class alignas(0x10) ANPC_Sub_fl_Simple_sit_Base_C : public ANPC_Sub_fl_Simple_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NPC_Sub_fl_Simple_sit_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NPC_Sub_fl_Simple_sit_Base_C")
	}
	static class ANPC_Sub_fl_Simple_sit_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPC_Sub_fl_Simple_sit_Base_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_ANPC_Sub_fl_Simple_sit_Base_C;

}

