#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Sub_ml_Simple_Base_sp_headache_loop

#include "Basic.hpp"

#include "NPC_Sub_ml_Simple_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPC_Sub_ml_Simple_Base_sp_headache_loop.NPC_Sub_ml_Simple_Base_sp_headache_loop_C
// 0x0000 (0x07A0 - 0x07A0)
class ANPC_Sub_ml_Simple_Base_sp_headache_loop_C final : public ANPC_Sub_ml_Simple_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NPC_Sub_ml_Simple_Base_sp_headache_loop_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NPC_Sub_ml_Simple_Base_sp_headache_loop_C")
	}
	static class ANPC_Sub_ml_Simple_Base_sp_headache_loop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPC_Sub_ml_Simple_Base_sp_headache_loop_C>();
	}
};
DUMPER7_ASSERTS_ANPC_Sub_ml_Simple_Base_sp_headache_loop_C;

}

