#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Sub_mm_IdleState_Fear

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPC_Sub_mm_IdleState_Fear.NPC_Sub_mm_IdleState_Fear_C
// 0x0000 (0x0360 - 0x0360)
class UNPC_Sub_mm_IdleState_Fear_C : public UHTAIIdleStateBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NPC_Sub_mm_IdleState_Fear_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NPC_Sub_mm_IdleState_Fear_C")
	}
	static class UNPC_Sub_mm_IdleState_Fear_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNPC_Sub_mm_IdleState_Fear_C>();
	}
};
DUMPER7_ASSERTS_UNPC_Sub_mm_IdleState_Fear_C;

}

