#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerInteractLayer_female051_BP

#include "Basic.hpp"

#include "HtPlayerInteractAnimLayerBase_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass PlayerInteractLayer_female051_BP.PlayerInteractLayer_female051_BP_C
// 0x0000 (0x0AB0 - 0x0AB0)
class UPlayerInteractLayer_female051_BP_C final : public UHtPlayerInteractAnimLayerBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PlayerInteractLayer_female051_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PlayerInteractLayer_female051_BP_C")
	}
	static class UPlayerInteractLayer_female051_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerInteractLayer_female051_BP_C>();
	}
};
DUMPER7_ASSERTS_UPlayerInteractLayer_female051_BP_C;

}

