#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SimplygonSettings

#include "Basic.hpp"


namespace SDK
{

// Enum SimplygonSettings.ERemeshingProcessorVersion
// NumValues: 0x0003
enum class ERemeshingProcessorVersion : uint8
{
	Default                                  = 0,
	Legacy                                   = 1,
	ERemeshingProcessorVersion_MAX           = 2,
};

// Enum SimplygonSettings.EDefaultTNBSimplygon
// NumValues: 0x0005
enum class EDefaultTNBSimplygon : uint8
{
	OrthonormalRightHanded                   = 0,
	Autodesk3dsMax                           = 1,
	OrthonormalLeftHanded                    = 2,
	MikkTSpace                               = 3,
	EDefaultTNBSimplygon_MAX                 = 4,
};

// Enum SimplygonSettings.EDistributionMethod
// NumValues: 0x0004
enum class EDistributionMethod : uint32
{
	SimplygonGrid                            = 0,
	FastBuild                                = 1,
	Incredibuild                             = 2,
	EDistributionMethod_MAX                  = 3,
};

// Enum SimplygonSettings.EGridAgentUtilizationMode
// NumValues: 0x0003
enum class EGridAgentUtilizationMode : uint32
{
	Default                                  = 0,
	Passthrough                              = 1,
	EGridAgentUtilizationMode_MAX            = 2,
};

// Enum SimplygonSettings.ELogLevel
// NumValues: 0x0003
enum class ELogLevel : uint32
{
	Info                                     = 0,
	Debug                                    = 1,
	ELogLevel_MAX                            = 2,
};

// Enum SimplygonSettings.EConcurrentTasksMode
// NumValues: 0x0003
enum class EConcurrentTasksMode : uint32
{
	Auto                                     = 0,
	Manual                                   = 1,
	EConcurrentTasksMode_MAX                 = 2,
};

}

