#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SM_searchlight_3

#include "Basic.hpp"

#include "SM_searchlight_3_classes.hpp"


namespace SDK
{

// Function SM_searchlight_3.SM_searchlight_3_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ASM_searchlight_3_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SM_searchlight_3_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

