#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tayge_Name_q110150

#include "Basic.hpp"


namespace SDK::Params
{

// Function Tayge_Name_q110150.Tayge_Name_q110150_C.ExecuteUbergraph_Tayge_Name_q110150
// 0x0008 (0x0008 - 0x0000)
struct Tayge_Name_q110150_C_ExecuteUbergraph_Tayge_Name_q110150 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDefaultChapterTip_ReturnValue;          // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Tayge_Name_q110150_C_ExecuteUbergraph_Tayge_Name_q110150;

}

