#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UDS_Cloud_Paint_Container_FogMap

#include "Basic.hpp"

#include "UDS_Cloud_Paint_Container_FogMap_classes.hpp"
#include "UDS_Cloud_Paint_Container_FogMap_parameters.hpp"


namespace SDK
{

// Function UDS_Cloud_Paint_Container_FogMap.UDS_Cloud_Paint_Container_FogMap_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AUDS_Cloud_Paint_Container_FogMap_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UDS_Cloud_Paint_Container_FogMap_C", "ReceiveEndPlay");

	Params::UDS_Cloud_Paint_Container_FogMap_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UDS_Cloud_Paint_Container_FogMap.UDS_Cloud_Paint_Container_FogMap_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AUDS_Cloud_Paint_Container_FogMap_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UDS_Cloud_Paint_Container_FogMap_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UDS_Cloud_Paint_Container_FogMap.UDS_Cloud_Paint_Container_FogMap_C.ExecuteUbergraph_UDS_Cloud_Paint_Container_FogMap
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AUDS_Cloud_Paint_Container_FogMap_C::ExecuteUbergraph_UDS_Cloud_Paint_Container_FogMap(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UDS_Cloud_Paint_Container_FogMap_C", "ExecuteUbergraph_UDS_Cloud_Paint_Container_FogMap");

	Params::UDS_Cloud_Paint_Container_FogMap_C_ExecuteUbergraph_UDS_Cloud_Paint_Container_FogMap Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

