#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Vehicle_SpeedOut1

#include "Basic.hpp"

#include "SkillEffect_HitOut_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Vehicle_SpeedOut1.Vehicle_SpeedOut1_C
// 0x0000 (0x01C0 - 0x01C0)
class UVehicle_SpeedOut1_C final : public USkillEffect_HitOut_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Vehicle_SpeedOut1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Vehicle_SpeedOut1_C")
	}
	static class UVehicle_SpeedOut1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVehicle_SpeedOut1_C>();
	}
};
DUMPER7_ASSERTS_UVehicle_SpeedOut1_C;

}

