#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_GamepadKeysTips

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WB_GamepadKeysTips.WB_GamepadKeysTips_C.ExecuteUbergraph_WB_GamepadKeysTips
// 0x0014 (0x0014 - 0x0000)
struct WB_GamepadKeysTips_C_ExecuteUbergraph_WB_GamepadKeysTips final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0004(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WB_GamepadKeysTips_C_ExecuteUbergraph_WB_GamepadKeysTips;

}

